(() => {
  "use strict";

  window.createHealerContextFactory = function createHealerContextFactory(options) {
    const {
      state,
      systems,
      data,
      config,
      balance,
      theme,
      spatial,
      TAU,
    } = options;

    const {
      CHARACTER_DEFS,
      ENEMY_DEFS,
      SKILL_DATA,
      STATUS_DATA,
      PASSIVE_DATA,
      LOADOUT_CONFIG,
      EQUIPMENT_DATA,
      MATERIAL_DATA,
      QUEST_DATA,
      TOWN_DATA,
    } = data;

    const {
      BATTLE_SPATIAL_SCALE,
      TOWN_WIDTH,
      TOWN_HEIGHT,
      BATTLE_SIDE_MARGIN,
      BATTLE_MIN_PLAY_HEIGHT,
      battlePx,
    } = spatial;

    const COLORS = theme.colors;
    const ULTIMATE_KEYS = theme.ultimateKeys;
    const STATUS_FULL_NAMES = theme.statusFullNames;
    const KEYBINDS = window.HEALER_KEYBINDS;
    const PLAYER_SKILL_SLOT_KEYS = Array.isArray(config && config.playerSkillSlotKeys)
      ? config.playerSkillSlotKeys
      : ["q", "w", "e", "r", "t"];
    const ITEM_SLOT_KEYS = Array.isArray(config && config.itemSlotKeys)
      ? config.itemSlotKeys
      : ["c", "v", "b", "n"];

    function callLater(systemName, methodName) {
      return (...args) => {
        const system = systems[systemName];
        const method = system && system[methodName];
        if (typeof method !== "function") {
          throw new Error(`Context dependency missing: ${systemName}.${methodName}`);
        }
        return method(...args);
      };
    }

    function getGameSettings() {
      if (!state.game.settings || typeof state.game.settings !== "object") {
        state.game.settings = {};
      }
      return state.game.settings;
    }

    function getKeybinds() {
      const settings = getGameSettings();
      if (!KEYBINDS) {
        return {};
      }
      return KEYBINDS.getSettingsKeybinds(settings);
    }

    function getKeybindLabel(actionId) {
      return KEYBINDS ? KEYBINDS.getKeybindLabel(getGameSettings(), actionId) : "";
    }

    function createGeometryContext() {
      return {
        TAU,
        view: state.view,
        town: state.town,
        party: state.party,
        enemies: state.enemies,
        TOWN_WIDTH,
        TOWN_HEIGHT,
        BATTLE_SPATIAL_SCALE,
        BATTLE_SIDE_MARGIN,
        BATTLE_MIN_PLAY_HEIGHT,
        battlePx,
        isFieldUnit: callLater("battleRuntime", "isFieldUnit"),
        isTargetableUnit: callLater("battleRuntime", "isTargetableUnit"),
      };
    }

    function createStoryContext() {
      return {
        getPlayerFirstName: callLater("profileSystem", "getPlayerFirstName"),
        getPlayerFullName: callLater("profileSystem", "getPlayerFullName"),
      };
    }

    function createProfileContext() {
      return {
        view: state.view,
        game: state.game,
        town: state.town,
        playerProfile: state.playerProfile,
        profileClickTargets: state.profileClickTargets,
        COLORS,
        getPlayer: () => state.player,
        getOpeningStory: callLater("storyData", "getOpeningStory"),
        startTownStory: callLater("townController", "startTownStory"),
      };
    }

    function createWalletContext() {
      return {
        game: state.game,
        MATERIAL_DATA,
      };
    }

    function createSaveContext() {
      return {
        state,
        game: state.game,
        town: state.town,
        player: state.player,
        party: state.party,
        playerProfile: state.playerProfile,
        updateProfileNameInput: callLater("profileSystem", "updateProfileNameInput"),
      };
    }

    function createLoadoutContext() {
      return {
        SKILL_DATA,
        PASSIVE_DATA,
        LOADOUT_CONFIG,
        EQUIPMENT_DATA,
        CHARACTER_DEFS,
        game: state.game,
        resolveEquipmentItem: callLater("equipmentSystem", "resolveItem"),
        getEquipmentUpgradeLevel: callLater("equipmentSystem", "getEquipmentUpgradeLevel"),
      };
    }

    function createEquipmentContext() {
      return {
        EQUIPMENT_DATA,
        game: state.game,
      };
    }

    function createUnitFactoryContext() {
      return {
        CHARACTER_DEFS,
        ENEMY_DEFS,
        MOOD_REFERENCE_HP_BY_ID: balance.moodReferenceHpById,
        MOOD_INITIAL: balance.moodInitial,
        DEFAULT_MP_REGEN_RATE: balance.defaultMpRegenRate,
        BASE_CRIT_CHANCE: balance.baseCritChance,
        BASE_CRIT_DAMAGE_RATE: balance.baseCritDamageRate,
        battlePx,
        getSkillSystem: () => systems.skillSystem,
        getActionCooldown: callLater("skillSystem", "getActionCooldown"),
        getDefaultLoadout: callLater("loadoutSystem", "getDefaultLoadout"),
        normalizeLoadout: callLater("loadoutSystem", "normalizeLoadout"),
        getEmptyEquipment: callLater("equipmentSystem", "getEmptyEquipment"),
        normalizeEquipment: callLater("equipmentSystem", "normalizeEquipment"),
      };
    }

    function createSkillContext() {
      return {
        get player() { return state.player; },
        get party() { return state.party; },
        get enemies() { return state.enemies; },
        get projectiles() { return state.projectiles; },
        get areas() { return state.areas; },
        get effects() { return state.effects; },
        canvasCtx: state.canvasCtx,
        TAU,
        view: state.view,
        input: state.input,
        game: state.game,
        PLAYER_SKILL_SLOT_KEYS,
        getKeybindLabel,
        COLORS,
        ACTION_GAP: balance.actionGap,
        ACTION_COOLDOWN_BASE: balance.actionCooldownBase,
        AI_IDLE_RECHECK: balance.aiIdleRecheck,
        MOOD_EVENT_MULT: balance.moodEventMult,
        MOOD_MULTI_HIT_MIN: balance.moodMultiHitMin,
        AUTO_ULTIMATE_ENEMY_DAMAGE_MULTIPLIER: balance.autoUltimateEnemyDamageMultiplier,
        AUTO_ULTIMATE_ENEMY_EFFECT_MULTIPLIER: balance.autoUltimateEnemyEffectMultiplier,
        BATTLE_SPATIAL_SCALE,
        battlePx,
        clamp: callLater("geometry", "clamp"),
        normalize: callLater("geometry", "normalize"),
        dist: callLater("geometry", "dist"),
        distPoint: callLater("geometry", "distPoint"),
        angleTo: callLater("geometry", "angleTo"),
        deg: callLater("geometry", "deg"),
        inFan: callLater("geometry", "inFan"),
        nearestAlive: callLater("geometry", "nearestAlive"),
        projectPoint: callLater("geometry", "projectPoint"),
        distanceToSegment: callLater("geometry", "distanceToSegment"),
        getMoodCooldown: callLater("battleStats", "getMoodCooldown"),
        getCommandActionCooldown: callLater("battleStats", "getCommandActionCooldown"),
        getEquipmentStatBonusSum: callLater("equipmentSystem", "getStatBonusSum"),
        hasPassive: callLater("loadoutSystem", "hasPassive"),
        applyMoodCommandBiasAuto: callLater("battleStats", "applyMoodCommandBiasAuto"),
        commitCommandBias: callLater("battleStats", "commitCommandBias"),
        beginMoodAction: callLater("battleStats", "beginMoodAction"),
        clampCommandBias: callLater("battleStats", "clampCommandBias"),
        getCastTime: callLater("battleStats", "getCastTime"),
        getSushiaCastTime: callLater("battleStats", "getSushiaCastTime"),
        applyMultiHitMoodBonus: callLater("battleStats", "applyMultiHitMoodBonus"),
        addMoodGain: callLater("battleStats", "addMoodGain"),
        getEffectiveAttack: callLater("battleStats", "getEffectiveAttack"),
        getEffectiveMagic: callLater("battleStats", "getEffectiveMagic"),
        dealDamage: callLater("combatSystem", "dealDamage"),
        awardOffensiveUltimate: callLater("combatSystem", "awardOffensiveUltimate"),
        awardSupportUltimate: callLater("combatSystem", "awardSupportUltimate"),
        canFriendlyFireAffect: callLater("combatSystem", "canFriendlyFireAffect"),
        getFriendlyFireEffectDurationMultiplier: callLater("combatSystem", "getFriendlyFireEffectDurationMultiplier"),
        healUnit: callLater("combatSystem", "healUnit"),
        addTelegraph: callLater("battleRuntime", "addTelegraph"),
        addBurst: callLater("battleRuntime", "addBurst"),
        addFloat: callLater("battleRuntime", "addFloat"),
        addSpeech: callLater("battleRuntime", "addSpeech"),
        slashEffect: callLater("battleRuntime", "slashEffect"),
        addShield: callLater("combatSystem", "addShield"),
        startPlayerCast: callLater("battleRuntime", "startPlayerCast"),
        getHoveredPartyMember: callLater("battleRuntime", "getHoveredPartyMember"),
        getHoveredEnemy: callLater("battleRuntime", "getHoveredEnemy"),
        getPriorityTarget: callLater("battleRuntime", "getPriorityTarget"),
        setPriorityTarget: callLater("battleRuntime", "setPriorityTarget"),
        isAvoidTarget: callLater("battleRuntime", "isAvoidTarget"),
        setAvoidTarget: callLater("battleRuntime", "setAvoidTarget"),
        cancelPlayerChannel: callLater("battleRuntime", "cancelPlayerChannel"),
        drawAimRangeCircle: callLater("renderer", "drawAimRangeCircle"),
        getBattleBounds: callLater("geometry", "getBattleBounds"),
        clampBattlePoint: callLater("geometry", "clampBattlePoint"),
        getSupportOrigin: callLater("battleRuntime", "getSupportOrigin"),
        isFieldUnit: callLater("battleRuntime", "isFieldUnit"),
        getFieldPartyMembers: callLater("battleRuntime", "getFieldPartyMembers"),
        getTargetablePartyMembers: callLater("battleRuntime", "getTargetablePartyMembers"),
        isActiveSkillEquipped: callLater("loadoutSystem", "isActiveSkillEquipped"),
        getEquippedActiveSkillKeys: callLater("loadoutSystem", "getEquippedActiveSkillKeys"),
        getEquippedActiveSkills: callLater("loadoutSystem", "getEquippedActiveSkills"),
        getEquippedUltimateSkillKey: callLater("loadoutSystem", "getEquippedUltimateSkillKey"),
        getEquippedUltimateSkill: callLater("loadoutSystem", "getEquippedUltimateSkill"),
        getSkillLevel: callLater("loadoutSystem", "getSkillLevel"),
      };
    }

    function createRenderContext() {
      return {
        canvasCtx: state.canvasCtx,
        TAU,
        TOWN_WIDTH,
        TOWN_HEIGHT,
        BATTLE_SPATIAL_SCALE,
        view: state.view,
        input: state.input,
        game: state.game,
        town: state.town,
        playerProfile: state.playerProfile,
        get profileNameInput() { return state.profileNameInput; },
        profileClickTargets: state.profileClickTargets,
        expandedStatusUnitIds: state.expandedStatusUnitIds,
        statusUiButtons: state.statusUiButtons,
        statusCardMetas: state.statusCardMetas,
        statusTooltipTargets: state.statusTooltipTargets,
        CHARACTER_DEFS,
        SKILL_DATA,
        PASSIVE_DATA,
        EQUIPMENT_DATA,
        MATERIAL_DATA,
        LOADOUT_CONFIG,
        player: state.player,
        party: state.party,
        enemies: state.enemies,
        projectiles: state.projectiles,
        telegraphs: state.telegraphs,
        areas: state.areas,
        effects: state.effects,
        COLORS,
        ACTION_GAP: balance.actionGap,
        MOOD_BASELINE: balance.moodBaseline,
        BASE_CRIT_CHANCE: balance.baseCritChance,
        BASE_CRIT_DAMAGE_RATE: balance.baseCritDamageRate,
        ULTIMATE_KEYS,
        STATUS_FULL_NAMES,
        STATUS_DATA,
        ITEM_SLOT_KEYS,
        KEYBINDS,
        getKeybinds,
        getKeybindLabel,
        COMMAND_BIAS_CONFIGS: balance.commandBiasConfigs,
        RIHAS_PASSIVE_MAX_STACKS: balance.rihasPassiveMaxStacks,
        RIHAS_PASSIVE_STACK_DURATION: balance.rihasPassiveStackDuration,
        SUSHIA_PASSIVE_MAX_STACKS: balance.sushiaPassiveMaxStacks,
        SUSHIA_PASSIVE_STACK_DURATION: balance.sushiaPassiveStackDuration,
        skillSystem: systems.skillSystem,
        itemSystem: systems.itemSystem,
        saveSystem: systems.saveSystem,
        tileMapSystem: systems.tileMapSystem,
        getGold: callLater("walletSystem", "getGold"),
        formatGold: callLater("walletSystem", "formatGold"),
        getItemCandidates: callLater("itemSystem", "getItemCandidates"),
        getCharacterItem: callLater("itemSystem", "getCharacterItem"),
        setCharacterItem: callLater("itemSystem", "setCharacterItem"),
        clearCharacterItem: callLater("itemSystem", "clearCharacterItem"),
        isSkillOwned: callLater("loadoutSystem", "isSkillOwned"),
        isPassiveOwned: callLater("loadoutSystem", "isPassiveOwned"),
        getSkillLevel: callLater("loadoutSystem", "getSkillLevel"),
        getPlayerFirstName: callLater("profileSystem", "getPlayerFirstName"),
        getPlayerFullName: callLater("profileSystem", "getPlayerFullName"),
        getPronounChoices: callLater("profileSystem", "getPronounChoices"),
        getProfileNameInputRects: callLater("profileSystem", "getProfileNameInputRects"),
        getProfileNameInputRect: callLater("profileSystem", "getProfileNameInputRect"),
        updateProfileNameInput: callLater("profileSystem", "updateProfileNameInput"),
        selectProfileGender: callLater("profileSystem", "selectProfileGender"),
        selectProfilePronoun: callLater("profileSystem", "selectProfilePronoun"),
        confirmProfileName: callLater("profileSystem", "confirmProfileName"),
        getTownBuilding: callLater("townController", "getTownBuilding"),
        getQuestTypes: callLater("townController", "getQuestTypes"),
        getQuestsByType: callLater("townController", "getQuestsByType"),
        getQuestById: callLater("townController", "getQuestById"),
        getBattleBounds: callLater("geometry", "getBattleBounds"),
        updateTelegraphDynamic: callLater("battleRuntime", "updateTelegraphDynamic"),
        battlePx,
        clamp: callLater("geometry", "clamp"),
        dist: callLater("geometry", "dist"),
        distPoint: callLater("geometry", "distPoint"),
        angleTo: callLater("geometry", "angleTo"),
        angleDiff: callLater("geometry", "angleDiff"),
        isFieldUnit: callLater("battleRuntime", "isFieldUnit"),
        getFieldPartyMembers: callLater("battleRuntime", "getFieldPartyMembers"),
        getTargetablePartyMembers: callLater("battleRuntime", "getTargetablePartyMembers"),
        getSupportOrigin: callLater("battleRuntime", "getSupportOrigin"),
        getMoodOutgoingDamageMultiplier: callLater("battleStats", "getMoodOutgoingDamageMultiplier"),
        getMoodIncomingDamageMultiplier: callLater("battleStats", "getMoodIncomingDamageMultiplier"),
        getCommandOutgoingDamageMultiplier: callLater("battleStats", "getCommandOutgoingDamageMultiplier"),
        getCommandIncomingDamageMultiplier: callLater("battleStats", "getCommandIncomingDamageMultiplier"),
        getMoodCooldownMultiplier: callLater("battleStats", "getMoodCooldownMultiplier"),
        getMoodCooldown: callLater("battleStats", "getMoodCooldown"),
        getMoodCastTimeMultiplier: callLater("battleStats", "getMoodCastTimeMultiplier"),
        getCastSpeed: callLater("battleStats", "getCastSpeed"),
        getSushiaCastTime: callLater("battleStats", "getSushiaCastTime"),
        getRihasPassiveDamageMultiplier: callLater("battleStats", "getRihasPassiveDamageMultiplier"),
        getRihasPassiveIncomingMultiplier: callLater("battleStats", "getRihasPassiveIncomingMultiplier"),
        getPhysicalDamageBoost: callLater("battleStats", "getPhysicalDamageBoost"),
        getMagicDamageBoost: callLater("battleStats", "getMagicDamageBoost"),
        getDamageBoost: callLater("battleStats", "getDamageBoost"),
        getDamageResistance: callLater("battleStats", "getDamageResistance"),
        getPhysicalDamageResistance: callLater("battleStats", "getPhysicalDamageResistance"),
        getMagicDamageResistance: callLater("battleStats", "getMagicDamageResistance"),
        getEffectiveAttack: callLater("battleStats", "getEffectiveAttack"),
        getEffectiveMagic: callLater("battleStats", "getEffectiveMagic"),
        getEffectiveDefense: callLater("battleStats", "getEffectiveDefense"),
        getEffectiveMagicDefense: callLater("battleStats", "getEffectiveMagicDefense"),
        getEffectiveStat: callLater("battleStats", "getEffectiveStat"),
        getEffectiveMoveSpeed: callLater("battleStats", "getEffectiveMoveSpeed"),
        getUltimateChargeRate: callLater("battleStats", "getUltimateChargeRate"),
        getEffectiveGuardChance: callLater("battleStats", "getEffectiveGuardChance"),
        getGuardDamageReductionRate: callLater("battleStats", "getGuardDamageReductionRate"),
        getEffectiveCritChance: callLater("battleStats", "getEffectiveCritChance"),
        getEffectiveCritDamageRate: callLater("battleStats", "getEffectiveCritDamageRate"),
        getHpRegenRate: callLater("battleStats", "getHpRegenRate"),
        getMpRegenRate: callLater("battleStats", "getMpRegenRate"),
        getElementKeys: callLater("equipmentSystem", "getElementKeys"),
        getElementName: callLater("equipmentSystem", "getElementName"),
        getElementShortName: callLater("equipmentSystem", "getElementShortName"),
        getNormalElement: callLater("equipmentSystem", "getNormalElement"),
        getElementBoostBonus: callLater("equipmentSystem", "getElementBoostBonus"),
        getElementResistanceBonus: callLater("equipmentSystem", "getElementResistanceBonus"),
        normalizeEquipment: callLater("equipmentSystem", "normalizeEquipment"),
        resolveEquipmentItem: callLater("equipmentSystem", "resolveItem"),
        getEquipmentInstancesByItemId: callLater("equipmentSystem", "getEquipmentInstancesByItemId"),
        getEquipmentItemRef: callLater("equipmentSystem", "getEquipmentItemRef"),
        getEquipmentBaseItemId: callLater("equipmentSystem", "getEquipmentBaseItemId"),
        getEquipmentOwnedCount: callLater("equipmentSystem", "getEquipmentOwnedCount"),
        getEquipmentUpgradeLevel: callLater("equipmentSystem", "getEquipmentUpgradeLevel"),
        getEquippedItems: callLater("equipmentSystem", "getEquippedItems"),
        getEquippedSlotItem: callLater("equipmentSystem", "getEquippedSlotItem"),
        getActiveSetEffects: callLater("equipmentSystem", "getActiveSetEffects"),
        getEquipmentStatBonusSum: callLater("equipmentSystem", "getStatBonusSum"),
        canEquipItem: callLater("equipmentSystem", "canEquip"),
        getActiveSlotLimit: callLater("loadoutSystem", "getActiveSlotLimit"),
        getDefaultLoadout: callLater("loadoutSystem", "getDefaultLoadout"),
        normalizeLoadout: callLater("loadoutSystem", "normalizeLoadout"),
        hasPassive: callLater("loadoutSystem", "hasPassive"),
        getEquippedActiveSkills: callLater("loadoutSystem", "getEquippedActiveSkills"),
        getEquippedPassive: callLater("loadoutSystem", "getEquippedPassive"),
      };
    }

    function createScreenContext() {
      return {
        canvas: state.canvas,
        canvasCtx: state.canvasCtx,
        view: state.view,
        game: state.game,
        clampTownPlayer: callLater("geometry", "clampTownPlayer"),
        updateTownCamera: callLater("townController", "updateTownCamera"),
        clampAllUnits: callLater("geometry", "clampAllUnits"),
        updateProfileNameInput: callLater("profileSystem", "updateProfileNameInput"),
      };
    }

    function createStatusControlsContext() {
      return {
        game: state.game,
        expandedStatusUnitIds: state.expandedStatusUnitIds,
        statusUiButtons: state.statusUiButtons,
        startPlayerAim: callLater("skillSystem", "startPlayerAim"),
        usePlayerCommand: callLater("skillSystem", "usePlayerCommand"),
        cancelPlayerAim: callLater("skillSystem", "cancelPlayerAim"),
        isPlayerControlLocked: callLater("skillSystem", "isPlayerControlLocked"),
        triggerUltimate: callLater("skillSystem", "triggerUltimate"),
        useItemSlot: callLater("itemSystem", "useItemSlot"),
        cancelItemAim: callLater("itemSystem", "cancelItemAim"),
      };
    }

    function createGameLoopContext() {
      return {
        game: state.game,
        update: callLater("battleRuntime", "update"),
        draw: callLater("renderer", "draw"),
      };
    }

    function createInputContext() {
      return {
        canvas: state.canvas,
        input: state.input,
        game: state.game,
        town: state.town,
        party: state.party,
        enemies: state.enemies,
        projectiles: state.projectiles,
        telegraphs: state.telegraphs,
        areas: state.areas,
        effects: state.effects,
        expandedStatusUnitIds: state.expandedStatusUnitIds,
        player: state.player,
        playerProfile: state.playerProfile,
        CHARACTER_DEFS,
        SKILL_DATA,
        PASSIVE_DATA,
        EQUIPMENT_DATA,
        LOADOUT_CONFIG,
        resize: systems.screenSystem.resize,
        startGameLoop: systems.gameLoop.start,
        startTown: callLater("townController", "startTown"),
        saveSystem: systems.saveSystem,
        getGold: callLater("walletSystem", "getGold"),
        formatGold: callLater("walletSystem", "formatGold"),
        canAffordGold: callLater("walletSystem", "canAffordGold"),
        spendGold: callLater("walletSystem", "spendGold"),
        handleProfileSetupKey: callLater("profileSystem", "handleProfileSetupKey"),
        handleProfileSetupClick: callLater("profileSystem", "handleProfileSetupClick"),
        interactTown: callLater("townController", "interactTown"),
        switchTownMap: callLater("townController", "switchTownMap"),
        closeTownPanel: callLater("townController", "closeTownPanel"),
        PLAYER_SKILL_SLOT_KEYS,
        ITEM_SLOT_KEYS,
        KEYBINDS,
        getKeybinds,
        getKeybindLabel,
        getPanelSkills: callLater("skillSystem", "getPanelSkills"),
        startPlayerAim: callLater("skillSystem", "startPlayerAim"),
        usePlayerCommand: callLater("skillSystem", "usePlayerCommand"),
        cancelPlayerAim: callLater("skillSystem", "cancelPlayerAim"),
        confirmPlayerAim: callLater("skillSystem", "confirmPlayerAim"),
        isPlayerControlLocked: callLater("skillSystem", "isPlayerControlLocked"),
        triggerUltimate: callLater("skillSystem", "triggerUltimate"),
        useItemSlot: callLater("itemSystem", "useItemSlot"),
        cancelItemAim: callLater("itemSystem", "cancelItemAim"),
        confirmItemAim: callLater("itemSystem", "confirmItemAim"),
        useInventoryItem: callLater("itemSystem", "useInventoryItem"),
        usePowerCrystalDFromBattleReward: callLater("itemSystem", "usePowerCrystalDFromBattleReward"),
        getItemCandidates: callLater("itemSystem", "getItemCandidates"),
        getCharacterItem: callLater("itemSystem", "getCharacterItem"),
        setCharacterItem: callLater("itemSystem", "setCharacterItem"),
        clearCharacterItem: callLater("itemSystem", "clearCharacterItem"),
        getItemInventoryCount: callLater("itemSystem", "getItemInventoryCount"),
        isSkillOwned: callLater("loadoutSystem", "isSkillOwned"),
        isPassiveOwned: callLater("loadoutSystem", "isPassiveOwned"),
        getPlayerFirstName: callLater("profileSystem", "getPlayerFirstName"),
        handleStatusUiClick: systems.statusControls.handleStatusUiClick,
        hasCommandBiasDrag: systems.statusControls.hasCommandBiasDrag,
        clearCommandBiasDrag: systems.statusControls.clearCommandBiasDrag,
        updateCommandBiasDrag: systems.statusControls.updateCommandBiasDrag,
        normalizeEquipment: callLater("equipmentSystem", "normalizeEquipment"),
        equipItem: callLater("equipmentSystem", "equipItem"),
        unequipSlot: callLater("equipmentSystem", "unequipSlot"),
        canEquipItem: callLater("equipmentSystem", "canEquip"),
        resolveEquipmentItem: callLater("equipmentSystem", "resolveItem"),
        getEquipmentItemRef: callLater("equipmentSystem", "getEquipmentItemRef"),
        getEquipmentBaseItemId: callLater("equipmentSystem", "getEquipmentBaseItemId"),
        getEquipmentOwnedCount: callLater("equipmentSystem", "getEquipmentOwnedCount"),
        getDefaultLoadout: callLater("loadoutSystem", "getDefaultLoadout"),
        normalizeLoadout: callLater("loadoutSystem", "normalizeLoadout"),
        setUnitLoadout: callLater("loadoutSystem", "setUnitLoadout"),
        getActiveSlotLimit: callLater("loadoutSystem", "getActiveSlotLimit"),
      };
    }

    function createTownContext() {
      return {
        input: state.input,
        game: state.game,
        town: state.town,
        player: state.player,
        playerProfile: state.playerProfile,
        party: state.party,
        enemies: state.enemies,
        projectiles: state.projectiles,
        telegraphs: state.telegraphs,
        areas: state.areas,
        effects: state.effects,
        tileMapSystem: systems.tileMapSystem,
        TOWN_DATA,
        STATUS_DATA,
        EQUIPMENT_DATA,
        MATERIAL_DATA,
        QUEST_DATA,
        TOWN_WIDTH,
        TOWN_HEIGHT,
        resetGame: callLater("battleSetup", "resetGame"),
        clampTownPlayer: callLater("geometry", "clampTownPlayer"),
        clamp: callLater("geometry", "clamp"),
        distPoint: callLater("geometry", "distPoint"),
        updateProfileNameInput: callLater("profileSystem", "updateProfileNameInput"),
        beginOpeningStory: callLater("profileSystem", "beginOpeningStory"),
        getPlayerFirstName: callLater("profileSystem", "getPlayerFirstName"),
        getPlayerFullName: callLater("profileSystem", "getPlayerFullName"),
        getMeetingStory: callLater("storyData", "getMeetingStory"),
        getKeybindLabel,
        getGold: callLater("walletSystem", "getGold"),
        formatGold: callLater("walletSystem", "formatGold"),
        canAffordGold: callLater("walletSystem", "canAffordGold"),
        spendGold: callLater("walletSystem", "spendGold"),
        addGold: callLater("walletSystem", "addGold"),
        getItemCandidates: callLater("itemSystem", "getItemCandidates"),
        getItemDef: callLater("itemSystem", "getItemDef"),
        getItemOwnedCount: callLater("itemSystem", "getItemOwnedCount"),
        getItemCapacity: callLater("itemSystem", "getItemCapacity"),
        addItem: callLater("itemSystem", "addItem"),
        resolveEquipmentItem: callLater("equipmentSystem", "resolveItem"),
        createEquipmentInstance: callLater("equipmentSystem", "createEquipmentInstance"),
        getEquipmentOwnedCount: callLater("equipmentSystem", "getEquipmentOwnedCount"),
        getEquipmentUpgradeLevel: callLater("equipmentSystem", "getEquipmentUpgradeLevel"),
        setEquipmentUpgradeLevel: callLater("equipmentSystem", "setEquipmentUpgradeLevel"),
        resetEquipmentUpgrade: callLater("equipmentSystem", "resetEquipmentUpgrade"),
        getEquipmentRandomStatUpgradeTarget: callLater("equipmentSystem", "getEquipmentRandomStatUpgradeTarget"),
        rerollEquipmentRandomStats: callLater("equipmentSystem", "rerollEquipmentRandomStats"),
        getEquipmentItemRef: callLater("equipmentSystem", "getEquipmentItemRef"),
        getEquipmentBaseItemId: callLater("equipmentSystem", "getEquipmentBaseItemId"),
        getEquipmentInstancesByItemId: callLater("equipmentSystem", "getEquipmentInstancesByItemId"),
      };
    }

    function createBattleSetupContext() {
      return {
        game: state.game,
        player: state.player,
        party: state.party,
        enemies: state.enemies,
        projectiles: state.projectiles,
        telegraphs: state.telegraphs,
        areas: state.areas,
        effects: state.effects,
        expandedStatusUnitIds: state.expandedStatusUnitIds,
        STATUS_DATA,
        COLORS,
        battlePx,
        getBattleBounds: callLater("geometry", "getBattleBounds"),
        getSupportOrigin: callLater("battleRuntime", "getSupportOrigin"),
        makePartyMember: callLater("unitFactory", "makePartyMember"),
        makeEnemy: callLater("unitFactory", "makeEnemy"),
        getUltimateCost: callLater("skillSystem", "getUltimateCost"),
        getEffectiveStat: callLater("battleStats", "getEffectiveStat"),
        normalizeEquipment: callLater("equipmentSystem", "normalizeEquipment"),
        normalizeLoadout: callLater("loadoutSystem", "normalizeLoadout"),
        clampBattlePoint: callLater("geometry", "clampBattlePoint"),
        clampAllUnits: callLater("geometry", "clampAllUnits"),
        addBurst: callLater("battleRuntime", "addBurst"),
        addFloat: callLater("battleRuntime", "addFloat"),
      };
    }

    function createBattleStatsContext() {
      return {
        COMMAND_BIAS_CONFIGS: balance.commandBiasConfigs,
        COMMAND_BIAS_AUTO_GRACE_ACTIONS: balance.commandBiasAutoGraceActions,
        MOOD_NATURAL_HP_STEPS: balance.moodNaturalHpSteps,
        MOOD_NATURAL_HP_BOTTOM_DELTA: balance.moodNaturalHpBottomDelta,
        MOOD_NO_DAMAGE_GAIN_BONUS_START: balance.moodNoDamageGainBonusStart,
        MOOD_NO_DAMAGE_GAIN_BONUS_MAX_TIME: balance.moodNoDamageGainBonusMaxTime,
        MOOD_NO_DAMAGE_GAIN_BONUS_MAX: balance.moodNoDamageGainBonusMax,
        MOOD_HIGH_GAIN_DAMPING_START: balance.moodHighGainDampingStart,
        MOOD_HIGH_GAIN_DAMPING_MULT: balance.moodHighGainDampingMult,
        MOOD_DISTANCE_BONUS_START: battlePx(balance.moodDistanceBonusStart),
        MOOD_DISTANCE_BONUS_END: battlePx(balance.moodDistanceBonusEnd),
        MOOD_DISTANCE_BONUS_MAX: balance.moodDistanceBonusMax,
        MOOD_MULTI_HIT_MIN: balance.moodMultiHitMin,
        MOOD_MULTI_HIT_BASE: balance.moodMultiHitBase,
        MOOD_DAMAGE_ACTION_CAP: balance.moodDamageActionCap,
        DEFAULT_MP_REGEN_RATE: balance.defaultMpRegenRate,
        CRIT_OVERFLOW_DAMAGE_RATE: balance.critOverflowDamageRate,
        ULPES_PASSIVE_CRIT_CHANCE_MULTIPLIER: balance.ulpesPassiveCritChanceMultiplier,
        ULPES_PASSIVE_CRIT_DAMAGE_BONUS_MULTIPLIER: balance.ulpesPassiveCritDamageBonusMultiplier,
        GUARD_DAMAGE_MULTIPLIER: balance.guardDamageMultiplier,
        GUARD_OVERFLOW_REDUCTION_RATE: balance.guardOverflowReductionRate,
        GUARD_MAX_DAMAGE_REDUCTION: balance.guardMaxDamageReduction,
        RIHAS_PASSIVE_MAX_STACKS: balance.rihasPassiveMaxStacks,
        RIHAS_PASSIVE_STACK_DURATION: balance.rihasPassiveStackDuration,
        RIHAS_PASSIVE_STACK_COOLDOWN: balance.rihasPassiveStackCooldown,
        RIHAS_PASSIVE_MAX_ATTACK_BONUS: balance.rihasPassiveMaxAttackBonus,
        RIHAS_PASSIVE_MAX_DEFENSE_BONUS: balance.rihasPassiveMaxDefenseBonus,
        clamp: callLater("geometry", "clamp"),
        dist: callLater("geometry", "dist"),
        hasPassive: callLater("loadoutSystem", "hasPassive"),
        getEquipmentEffectiveStat: callLater("equipmentSystem", "getEffectiveStat"),
        getEquipmentStatBonusSum: callLater("equipmentSystem", "getStatBonusSum"),
        getEquipmentFlatStatBonusSum: callLater("equipmentSystem", "getFlatStatBonusSum"),
      };
    }

    function createCombatContext() {
      return {
        player: state.player,
        game: state.game,
        COLORS,
        ACTION_GAP: balance.actionGap,
        SUSHIA_PASSIVE_MAX_STACKS: balance.sushiaPassiveMaxStacks,
        SUSHIA_PASSIVE_STACK_DURATION: balance.sushiaPassiveStackDuration,
        SUSHIA_PASSIVE_STACK_COOLDOWN: balance.sushiaPassiveStackCooldown,
        MOOD_DAMAGE_DEALT_RATE: balance.moodDamageDealtRate,
        MOOD_DAMAGE_DEALT_MULT: balance.moodDamageDealtMult,
        MOOD_DAMAGE_HP_RATIO_GAIN: balance.moodDamageHpRatioGain,
        MOOD_DAMAGE_HIT_CAP: balance.moodDamageHitCap,
        MOOD_DAMAGE_TAKEN_RATE: balance.moodDamageTakenRate,
        MOOD_DAMAGE_TAKEN_BASE_LOSS: balance.moodDamageTakenBaseLoss,
        MOOD_HEAL_RATE: balance.moodHealRate,
        MOOD_QUICK_HEAL_BONUS: balance.moodQuickHealBonus,
        MOOD_EVENT_MULT: balance.moodEventMult,
        MOOD_KILL_BONUS: balance.moodKillBonus,
        FRIENDLY_FIRE_MOOD_SAFE_LIMIT: balance.friendlyFireMoodSafeLimit,
        FRIENDLY_FIRE_MOOD_MAX: balance.friendlyFireMoodMax,
        FRIENDLY_FIRE_MIN_DAMAGE_MULTIPLIER: balance.friendlyFireMinDamageMultiplier,
        FRIENDLY_FIRE_MAX_DAMAGE_MULTIPLIER: balance.friendlyFireMaxDamageMultiplier,
        FRIENDLY_FIRE_LOW_EFFECT_DURATION_MULTIPLIER: balance.friendlyFireLowEffectDurationMultiplier,
        FRIENDLY_FIRE_HIGH_EFFECT_DURATION_MULTIPLIER: balance.friendlyFireHighEffectDurationMultiplier,
        HILMENT_SELF_HEAL_RATIO: balance.hilmentSelfHealRatio,
        clamp: callLater("geometry", "clamp"),
        addFloat: callLater("battleRuntime", "addFloat"),
        addBurst: callLater("battleRuntime", "addBurst"),
        cancelPlayerChannel: callLater("battleRuntime", "cancelPlayerChannel"),
        cancelPlayerCast: callLater("battleRuntime", "cancelPlayerCast"),
        getMoodOutgoingDamageMultiplier: callLater("battleStats", "getMoodOutgoingDamageMultiplier"),
        getMoodIncomingDamageMultiplier: callLater("battleStats", "getMoodIncomingDamageMultiplier"),
        getCommandOutgoingDamageMultiplier: callLater("battleStats", "getCommandOutgoingDamageMultiplier"),
        getCommandIncomingDamageMultiplier: callLater("battleStats", "getCommandIncomingDamageMultiplier"),
        getRihasPassiveDamageMultiplier: callLater("battleStats", "getRihasPassiveDamageMultiplier"),
        getRihasPassiveIncomingMultiplier: callLater("battleStats", "getRihasPassiveIncomingMultiplier"),
        getPhysicalDamageBoost: callLater("battleStats", "getPhysicalDamageBoost"),
        getMagicDamageBoost: callLater("battleStats", "getMagicDamageBoost"),
        getDamageBoost: callLater("battleStats", "getDamageBoost"),
        getDamageResistance: callLater("battleStats", "getDamageResistance"),
        getPhysicalDamageResistance: callLater("battleStats", "getPhysicalDamageResistance"),
        getMagicDamageResistance: callLater("battleStats", "getMagicDamageResistance"),
        getGuardDamageMultiplier: callLater("battleStats", "getGuardDamageMultiplier"),
        getUltimateChargeRate: callLater("battleStats", "getUltimateChargeRate"),
        getEffectiveGuardChance: callLater("battleStats", "getEffectiveGuardChance"),
        getEffectiveCritChance: callLater("battleStats", "getEffectiveCritChance"),
        getCritDamageMultiplier: callLater("battleStats", "getCritDamageMultiplier"),
        getActiveSetEffects: callLater("equipmentSystem", "getActiveSetEffects"),
        getUltimateCost: callLater("skillSystem", "getUltimateCost"),
        getEffectiveAttack: callLater("battleStats", "getEffectiveAttack"),
        getEffectiveDefense: callLater("battleStats", "getEffectiveDefense"),
        getEffectiveMagicDefense: callLater("battleStats", "getEffectiveMagicDefense"),
        addRihasPassiveStack: callLater("battleStats", "addRihasPassiveStack"),
        getElementOutgoingDamageMultiplier: callLater("equipmentSystem", "getElementOutgoingDamageMultiplier"),
        getElementIncomingDamageMultiplier: callLater("equipmentSystem", "getElementIncomingDamageMultiplier"),
        getMoodDistanceMultiplier: callLater("battleStats", "getMoodDistanceMultiplier"),
        getHpRatio: callLater("battleStats", "getHpRatio"),
        getMoodReferenceHp: callLater("battleStats", "getMoodReferenceHp"),
        addMoodActionGain: callLater("battleStats", "addMoodActionGain"),
        addMoodGain: callLater("battleStats", "addMoodGain"),
        addMoodLoss: callLater("battleStats", "addMoodLoss"),
        hasPassive: callLater("loadoutSystem", "hasPassive"),
      };
    }

    function createBattleAiContext() {
      return {
        party: state.party,
        player: state.player,
        enemies: state.enemies,
        telegraphs: state.telegraphs,
        areas: state.areas,
        skillSystem: systems.skillSystem,
        getItemSystem: () => systems.itemSystem,
        MOOD_BASELINE: balance.moodBaseline,
        COMMAND_BIAS_PREFERRED_RANGES: balance.commandBiasPreferredRanges,
        MOOD_PREFERRED_RANGE_HIGH: balance.moodPreferredRangeHigh,
        MOOD_PREFERRED_RANGE_LOW: balance.moodPreferredRangeLow,
        TELEGRAPH_AVOID_PADDING: battlePx(balance.telegraphAvoidPadding),
        TELEGRAPH_AVOID_SPEED_MULT: balance.telegraphAvoidSpeedMult,
        battlePx,
        clamp: callLater("geometry", "clamp"),
        dist: callLater("geometry", "dist"),
        distPoint: callLater("geometry", "distPoint"),
        normalize: callLater("geometry", "normalize"),
        angleDiff: callLater("geometry", "angleDiff"),
        nearestAlive: callLater("geometry", "nearestAlive"),
        clampUnit: callLater("geometry", "clampUnit"),
        getBattleBounds: callLater("geometry", "getBattleBounds"),
        updateTelegraphDynamic: callLater("battleRuntime", "updateTelegraphDynamic"),
        getTargetablePartyMembers: callLater("battleRuntime", "getTargetablePartyMembers"),
        getPriorityTarget: callLater("battleRuntime", "getPriorityTarget"),
        isAvoidTarget: callLater("battleRuntime", "isAvoidTarget"),
        getEffectiveMoveSpeed: callLater("battleStats", "getEffectiveMoveSpeed"),
        getEquippedSlotItem: callLater("equipmentSystem", "getEquippedSlotItem"),
        triggerUltimate: callLater("skillSystem", "triggerUltimate"),
        setActionCooldown: callLater("skillSystem", "setActionCooldown"),
      };
    }


    function createItemContext() {
      return {
        canvasCtx: state.canvasCtx,
        TAU,
        game: state.game,
        player: state.player,
        party: state.party,
        enemies: state.enemies,
        input: state.input,
        ITEM_SLOT_KEYS,
        ACTION_GAP: balance.actionGap,
        battlePx,
        dist: callLater("geometry", "dist"),
        normalize: callLater("geometry", "normalize"),
        clampUnit: callLater("geometry", "clampUnit"),
        getEffectiveMoveSpeed: callLater("battleStats", "getEffectiveMoveSpeed"),
        healUnit: callLater("combatSystem", "healUnit"),
        addFloat: callLater("battleRuntime", "addFloat"),
        addBurst: callLater("battleRuntime", "addBurst"),
        getHoveredPartyMember: callLater("battleRuntime", "getHoveredPartyMember"),
        getSupportOrigin: callLater("battleRuntime", "getSupportOrigin"),
        cancelPlayerAim: callLater("skillSystem", "cancelPlayerAim"),
        isPlayerControlLocked: callLater("skillSystem", "isPlayerControlLocked"),
        setActionCooldown: callLater("skillSystem", "setActionCooldown"),
        acquireOrUpgradeSkill: callLater("loadoutSystem", "acquireOrUpgradeSkill"),
        addGold: callLater("walletSystem", "addGold"),
        formatGold: callLater("walletSystem", "formatGold"),
      };
    }
    function createBattleRuntimeContext() {
      return {
        view: state.view,
        input: state.input,
        game: state.game,
        player: state.player,
        party: state.party,
        enemies: state.enemies,
        projectiles: state.projectiles,
        telegraphs: state.telegraphs,
        areas: state.areas,
        effects: state.effects,
        skillSystem: systems.skillSystem,
        getItemSystem: () => systems.itemSystem,
        ACTION_GAP: balance.actionGap,
        SHIELD_MOOD_GAIN_PER_SEC: balance.shieldMoodGainPerSec,
        battlePx,
        clamp: callLater("geometry", "clamp"),
        distPoint: callLater("geometry", "distPoint"),
        getBattleBounds: callLater("geometry", "getBattleBounds"),
        updateTown: callLater("townController", "updateTown"),
        updatePartyAi: callLater("battleAi", "updatePartyAi"),
        updateEnemyAi: callLater("battleAi", "updateEnemyAi"),
        separateUnits: callLater("geometry", "separateUnits"),
        spawnRearVanguardWave: callLater("battleSetup", "spawnRearVanguardWave"),
        regenerateHp: callLater("battleStats", "regenerateHp"),
        regenerateMp: callLater("battleStats", "regenerateMp"),
        getUltimateChargeRate: callLater("battleStats", "getUltimateChargeRate"),
        getMoodNaturalDelta: callLater("battleStats", "getMoodNaturalDelta"),
        applyCommandMoodDelta: callLater("battleStats", "applyCommandMoodDelta"),
        applyMoodHighGainDamping: callLater("battleStats", "applyMoodHighGainDamping"),
        addMoodGain: callLater("battleStats", "addMoodGain"),
        updateDelayedDamage: callLater("combatSystem", "updateDelayedDamage"),
        updateRihasPassiveStacks: callLater("battleStats", "updateRihasPassiveStacks"),
        dealDamage: callLater("combatSystem", "dealDamage"),
        awardOffensiveUltimate: callLater("combatSystem", "awardOffensiveUltimate"),
        awardSupportUltimate: callLater("combatSystem", "awardSupportUltimate"),
        canFriendlyFireAffect: callLater("combatSystem", "canFriendlyFireAffect"),
        getFriendlyFireEffectDurationMultiplier: callLater("combatSystem", "getFriendlyFireEffectDurationMultiplier"),
        healUnit: callLater("combatSystem", "healUnit"),
        addGold: callLater("walletSystem", "addGold"),
        formatGold: callLater("walletSystem", "formatGold"),
        addItem: callLater("itemSystem", "addItem"),
        hasPassive: callLater("loadoutSystem", "hasPassive"),
      };
    }

    return {
      createGeometryContext,
      createStoryContext,
      createProfileContext,
      createWalletContext,
      createSaveContext,
      createLoadoutContext,
      createEquipmentContext,
      createUnitFactoryContext,
      createSkillContext,
      createRenderContext,
      createScreenContext,
      createStatusControlsContext,
      createGameLoopContext,
      createInputContext,
      createTownContext,
      createBattleSetupContext,
      createBattleStatsContext,
      createCombatContext,
      createBattleAiContext,
      createItemContext,
      createBattleRuntimeContext,
    };
  };
})();
