(() => {
  "use strict";

  // Map data edited by map collaborators.
  // Tile images are optional for now. When assets are ready, set image to a path
  // such as "map/img_tile/forest/grass.png".
  window.HEALER_TILE_DEFS = {
    test_grass: {
      id: "test_grass",
      name: "テスト",
      image: "map/img_tile/rpg_village/grass_base_01.png",
      passable: true,
      tags: ["ground"],
    },
    grass: {
      id: "grass",
      name: "草地",
      image: "map/img_tile/base_seamless/grass_plain_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassPlain2: {
      id: "grassPlain2",
      name: "草地2",
      image: "map/img_tile/base_seamless/grass_plain_02.png",
      passable: true,
      tags: ["ground", "grass", "plain"],
    },
    grassFlower: {
      id: "grassFlower",
      name: "花の草地",
      image: "map/img_tile/rpg_village/grass_flower_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    grassBase: {
      id: "grassBase",
      name: "草地 ベース",
      image: "map/img_tile/rpg_village/grass_base_01.png",
      passable: true,
      tags: ["ground", "grass", "plain"],
    },
    grassDeep: {
      id: "grassDeep",
      name: "濃い草地",
      image: "map/img_tile/base_seamless/grass_dark_plain_01.png",
      passable: true,
      tags: ["ground", "deepGrass"],
    },
    grassPatchySoil: {
      id: "grassPatchySoil",
      name: "土まじりの草地",
      image: "map/img_tile/rpg_village/grass_patchy_soil_01.png",
      passable: true,
      tags: ["ground", "blend"],
    },
    road: {
      id: "road",
      name: "道",
      image: "map/img_tile/base_seamless/road_plain_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    dirtGrassBlend: {
      id: "dirtGrassBlend",
      name: "土と草の境目",
      image: "map/img_tile/rpg_village/dirt_grass_blend_01.png",
      passable: true,
      tags: ["ground", "road", "blend"],
    },
    dirtPathCenter: {
      id: "dirtPathCenter",
      name: "土の道 中央",
      image: "map/img_tile/rpg_village/dirt_path_center_01.png",
      passable: true,
      tags: ["ground", "road", "dirt"],
    },
    dirtPathDetail: {
      id: "dirtPathDetail",
      name: "土の道 模様",
      image: "map/img_tile/rpg_village/dirt_path_detail_01.png",
      passable: true,
      tags: ["ground", "road", "dirt", "decoration"],
    },
    dirtPathLeft: {
      id: "dirtPathLeft",
      name: "土の道 左寄せ",
      image: "map/img_tile/rpg_village/dirt_path_left_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    soil: {
      id: "soil",
      name: "土",
      image: "map/img_tile/base_seamless/soil_plain_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassOverSoilPatch: {
      id: "grassOverSoilPatch",
      name: "草かぶせ土",
      image: "map/img_tile/grass_over_soil_patch.png",
      passable: true,
      tags: ["overlay", "ground", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeTop: {
      id: "grassEdgeTop",
      name: "草境界 上",
      image: "map/img_tile/grass_edge_top.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeBottom: {
      id: "grassEdgeBottom",
      name: "草境界 下",
      image: "map/img_tile/grass_edge_bottom.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeLeft: {
      id: "grassEdgeLeft",
      name: "草境界 左",
      image: "map/img_tile/grass_edge_left.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeRight: {
      id: "grassEdgeRight",
      name: "草境界 右",
      image: "map/img_tile/grass_edge_right.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    floor: {
      id: "floor",
      name: "木の床",
      image: "map/img_tile/rpg_village_extra/wood_plank_floor_01.png",
      passable: true,
      tags: ["ground", "indoor", "wood"],
    },
    wall: {
      id: "wall",
      name: "崖の壁",
      image: "map/img_tile/rpg_village_extra/cliff_wall_01.png",
      passable: false,
      tags: ["terrainBlock", "wall", "block"],
    },
    tree: {
      id: "tree",
      name: "広葉樹",
      image: "map/img_tile/rpg_objects/tree_leafy_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    forestWallLeaf: {
      id: "forestWallLeaf",
      name: "森の壁 葉",
      image: "map/img_tile/rpg_village/forest_wall_leaf_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestWallPine: {
      id: "forestWallPine",
      name: "森の壁 松",
      image: "map/img_tile/rpg_village/forest_wall_pine_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestHedgeOpen: {
      id: "forestHedgeOpen",
      name: "森の入口",
      image: "map/img_tile/rpg_village/forest_hedge_open_01.png",
      passable: true,
      tags: ["ground", "forest", "nature"],
    },
    shrubCluster: {
      id: "shrubCluster",
      name: "低木",
      image: "map/img_tile/rpg_objects/bush_01.png",
      passable: false,
      tags: ["object", "bush", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    villageShrubCluster: {
      id: "villageShrubCluster",
      name: "茂み",
      image: "map/img_tile/rpg_village/shrub_cluster_01.png",
      passable: false,
      tags: ["terrainBlock", "bush", "block", "nature"],
    },
    rock: {
      id: "rock",
      name: "岩",
      image: "map/img_tile/rpg_objects/rock_cluster_01.png",
      passable: false,
      tags: ["object", "rock", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    water: {
      id: "water",
      name: "水",
      image: "map/img_tile/base_seamless/water_plain_01.png",
      passable: false,
      tags: ["water", "block"],
    },
    waterDeep: {
      id: "waterDeep",
      name: "深い水",
      image: "map/img_tile/rpg_village/water_deep_01.png",
      passable: false,
      tags: ["water", "deep", "block"],
    },
    waterShore: {
      id: "waterShore",
      name: "水辺",
      image: "map/img_tile/rpg_village/water_shore_01.png",
      passable: false,
      tags: ["water", "shore", "block"],
    },
    flowerMeadow: {
      id: "flowerMeadow",
      name: "花畑",
      image: "map/img_tile/rpg_village/flower_meadow_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    darkGrass: {
      id: "darkGrass",
      name: "暗い草地",
      image: "map/img_tile/rpg_village_extra/dark_grass_01.png",
      passable: true,
      tags: ["ground", "grass"],
    },
    wildflowerMeadow: {
      id: "wildflowerMeadow",
      name: "野花の草地",
      image: "map/img_tile/rpg_village_extra/wildflower_meadow_02.png",
      passable: true,
      tags: ["ground", "decoration", "flower"],
    },
    mossyGrass: {
      id: "mossyGrass",
      name: "苔の草地",
      image: "map/img_tile/rpg_village_extra/mossy_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "moss"],
    },
    wornGrass: {
      id: "wornGrass",
      name: "すり減った草地",
      image: "map/img_tile/rpg_village_extra/worn_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "blend"],
    },
    cobblestonePath: {
      id: "cobblestonePath",
      name: "石畳",
      image: "map/img_tile/rpg_village_extra/cobblestone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    crackedStonePath: {
      id: "crackedStonePath",
      name: "ひび割れ石道",
      image: "map/img_tile/rpg_village_extra/cracked_stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    stonePlain: {
      id: "stonePlain",
      name: "石地面",
      image: "map/img_tile/base_seamless/stone_plain_01.png",
      passable: true,
      tags: ["ground", "road", "stone", "plain"],
    },
    stonePath: {
      id: "stonePath",
      name: "石の道",
      image: "map/img_tile/rpg_village/stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    farmRows: {
      id: "farmRows",
      name: "畑",
      image: "map/img_tile/rpg_village_extra/farm_rows_01.png",
      passable: true,
      tags: ["ground", "farm"],
    },
    sandGround: {
      id: "sandGround",
      name: "砂地",
      image: "map/img_tile/rpg_village_extra/sand_ground_01.png",
      passable: true,
      tags: ["ground", "sand"],
    },
    mudGround: {
      id: "mudGround",
      name: "泥地",
      image: "map/img_tile/rpg_village_extra/mud_ground_01.png",
      passable: true,
      tags: ["ground", "mud"],
    },
    shallowWater: {
      id: "shallowWater",
      name: "浅瀬",
      image: "map/img_tile/rpg_village_extra/shallow_water_01.png",
      passable: true,
      tags: ["ground", "water", "shallow"],
    },
    marshGrass: {
      id: "marshGrass",
      name: "湿地草",
      image: "map/img_tile/rpg_village_extra/marsh_grass_01.png",
      passable: true,
      tags: ["ground", "marsh"],
    },
    cliffTopGrass: {
      id: "cliffTopGrass",
      name: "崖上草地",
      image: "map/img_tile/rpg_village_extra/cliff_top_grass_01.png",
      passable: true,
      tags: ["ground", "cliff"],
    },
    forestShadowGround: {
      id: "forestShadowGround",
      name: "森の影",
      image: "map/img_tile/rpg_village_extra/forest_shadow_ground_01.png",
      passable: true,
      tags: ["ground", "forest", "shadow"],
    },
    plazaEarth: {
      id: "plazaEarth",
      name: "広場の土",
      image: "map/img_tile/rpg_village_extra/plaza_earth_01.png",
      passable: true,
      tags: ["ground", "road", "village"],
    },
    pineTree: {
      id: "pineTree",
      name: "松",
      image: "map/img_tile/rpg_objects/tree_pine_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    flowerPatchObject: {
      id: "flowerPatchObject",
      name: "花壇",
      image: "map/img_tile/rpg_objects/flower_patch_01.png",
      passable: true,
      tags: ["object", "decoration", "flower"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stump: {
      id: "stump",
      name: "切り株",
      image: "map/img_tile/rpg_objects/stump_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fallenLog: {
      id: "fallenLog",
      name: "倒木",
      image: "map/img_tile/rpg_objects/fallen_log_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    weeds: {
      id: "weeds",
      name: "雑草",
      image: "map/img_tile/rpg_objects/weeds_01.png",
      passable: true,
      tags: ["object", "decoration", "grass"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fence: {
      id: "fence",
      name: "柵",
      image: "map/img_tile/rpg_objects/fence_01.png",
      passable: false,
      tags: ["object", "fence", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    crate: {
      id: "crate",
      name: "木箱",
      image: "map/img_tile/rpg_objects/crate_01.png",
      passable: false,
      tags: ["object", "box", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    barrel: {
      id: "barrel",
      name: "樽",
      image: "map/img_tile/rpg_objects/barrel_01.png",
      passable: false,
      tags: ["object", "barrel", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    well: {
      id: "well",
      name: "井戸",
      image: "map/img_tile/rpg_objects/well_01.png",
      passable: false,
      tags: ["object", "well", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    lampPost: {
      id: "lampPost",
      name: "街灯",
      image: "map/img_tile/rpg_objects/lamp_post_01.png",
      passable: false,
      tags: ["object", "lamp", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stoneMarker: {
      id: "stoneMarker",
      name: "石碑",
      image: "map/img_tile/rpg_objects/stone_marker_01.png",
      passable: false,
      tags: ["object", "stone", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    bridgePlank: {
      id: "bridgePlank",
      name: "木の橋",
      image: "map/img_tile/rpg_objects/bridge_plank_01.png",
      passable: true,
      tags: ["object", "bridge", "wood"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -24,
    },
    door: {
      id: "door",
      name: "出入口",
      image: null,
      passable: true,
      tags: ["event", "door"],
    },
    sign: {
      id: "sign",
      name: "看板",
      image: "map/img_tile/rpg_objects/signpost_01.png",
      passable: false,
      tags: ["object", "event", "decoration", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    armorShopFront: {
      id: "armorShopFront",
      name: "防具屋",
      image: "map/img_tile/town_objects_front/armor_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "armor", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    weaponShopFront: {
      id: "weaponShopFront",
      name: "武器屋",
      image: "map/img_tile/town_objects_front/weapon_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "weapon", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    innFront: {
      id: "innFront",
      name: "宿屋",
      image: "map/img_tile/town_objects_front/inn_front_3x2.png",
      passable: false,
      tags: ["object", "building", "inn", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    requestOfficeFront: {
      id: "requestOfficeFront",
      name: "依頼所",
      image: "map/img_tile/town_objects_front/request_office_front_3x2.png",
      passable: false,
      tags: ["object", "building", "requestOffice", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    itemShopFront: {
      id: "itemShopFront",
      name: "アイテム屋",
      image: "map/img_tile/town_objects_front/item_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "item", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    townHouseFront: {
      id: "townHouseFront",
      name: "町の民家 正面",
      image: "map/img_tile/town_objects_front/town_house_front_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    townHouseSideLeft: {
      id: "townHouseSideLeft",
      name: "町の民家 左向き",
      image: "map/img_tile/town_objects_front/town_house_side_left_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    townHouseSideRight: {
      id: "townHouseSideRight",
      name: "町の民家 右向き",
      image: "map/img_tile/town_objects_front/town_house_side_right_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
  };

  const GENERATED_GROUND_GROUPS = [
    {
      idPrefix: "cityTile",
      folder: "city_generated",
      tag: "city",
      names: [
        "都市タイル 明るい石畳",
        "都市タイル 暗い石畳",
        "都市タイル 整った敷石",
        "都市タイル 紋章広場",
        "都市タイル 赤レンガ",
        "都市タイル 斜めレンガ",
        "都市タイル 古い石畳",
        "都市タイル 大判石床",
        "都市タイル 縁石道路",
        "都市タイル 角縁石道路",
        "都市タイル 水路",
        "都市タイル 水路角",
        "都市タイル 通路石床",
        "都市タイル 赤い屋根",
        "都市タイル 青い屋根",
        "都市タイル 白い装飾床",
      ],
    },
    {
      idPrefix: "townTile",
      folder: "town_generated",
      tag: "town",
      label: "街タイル",
    },
    {
      idPrefix: "villageTile",
      folder: "village_generated",
      tag: "village",
      label: "村タイル",
    },
    {
      idPrefix: "fieldTile",
      folder: "field_generated",
      tag: "field",
      label: "自然タイル",
    },
    {
      idPrefix: "demonCastleTile",
      folder: "demon_castle_generated",
      tag: "demonCastle",
      label: "魔王城タイル",
    },
  ];

  function padTileNumber(value) {
    return String(value).padStart(2, "0");
  }

  function createGeneratedGroundTiles() {
    const defs = {};

    GENERATED_GROUND_GROUPS.forEach((group) => {
      for (let index = 1; index <= 16; index += 1) {
        const id = `${group.idPrefix}${padTileNumber(index)}`;
        const row = padTileNumber(Math.floor((index - 1) / 4) + 1);
        const col = padTileNumber(((index - 1) % 4) + 1);
        const name = group.names ? group.names[index - 1] : `${group.label} ${padTileNumber(index)}`;

        defs[id] = {
          id,
          name,
          image: `map/img_tile/generated_ground/${group.folder}/tile_${row}_${col}.png`,
          passable: true,
          tags: ["ground", "generated", group.tag],
        };
      }
    });

    return defs;
  }

  Object.assign(window.HEALER_TILE_DEFS, createGeneratedGroundTiles(), {
    cityRequestOfficeFront: {
      id: "cityRequestOfficeFront",
      name: "都市部 依頼所",
      image: "map/img_tile/city_objects_front/city_request_office_front.png",
      passable: false,
      tags: ["object", "building", "requestOffice", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    cityArmorShopFront: {
      id: "cityArmorShopFront",
      name: "都市部 防具屋",
      image: "map/img_tile/city_objects_front/city_armor_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "armor", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    cityInnFront: {
      id: "cityInnFront",
      name: "都市部 宿屋",
      image: "map/img_tile/city_objects_front/city_inn_front.png",
      passable: false,
      tags: ["object", "building", "inn", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    cityWeaponShopFront: {
      id: "cityWeaponShopFront",
      name: "都市部 武器屋",
      image: "map/img_tile/city_objects_front/city_weapon_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "weapon", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    cityItemShopFront: {
      id: "cityItemShopFront",
      name: "都市部 アイテム屋",
      image: "map/img_tile/city_objects_front/city_item_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "item", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
  });
})();
