(() => {
  "use strict";

  // Map data edited by map collaborators.
  // Tile images are optional for now. When assets are ready, set image to a path
  // such as "map/img_tile/forest/grass.png".
  window.HEALER_TILE_DEFS = {
    grass: {
      id: "grass",
      name: "草地",
      image: "map/img_tile/base_seamless/grass_plain_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassPlain2: {
      id: "grassPlain2",
      name: "Grass plain 2",
      image: "map/img_tile/base_seamless/grass_plain_02.png",
      passable: true,
      tags: ["ground", "grass", "plain"],
    },
    grassFlower: {
      id: "grassFlower",
      name: "花つき草地",
      image: "map/img_tile/rpg_village/grass_flower_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    grassDeep: {
      id: "grassDeep",
      name: "濃い草地",
      image: "map/img_tile/base_seamless/grass_dark_plain_01.png",
      passable: true,
      tags: ["ground", "deepGrass"],
    },
    grassPatchySoil: {
      id: "grassPatchySoil",
      name: "土まじり草地",
      image: "map/img_tile/rpg_village/grass_patchy_soil_01.png",
      passable: true,
      tags: ["ground", "blend"],
    },
    road: {
      id: "road",
      name: "道",
      image: "map/img_tile/base_seamless/road_plain_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    dirtGrassBlend: {
      id: "dirtGrassBlend",
      name: "草土なじみ",
      image: "map/img_tile/rpg_village/dirt_grass_blend_01.png",
      passable: true,
      tags: ["ground", "road", "blend"],
    },
    dirtPathLeft: {
      id: "dirtPathLeft",
      name: "土道・端",
      image: "map/img_tile/rpg_village/dirt_path_left_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    soil: {
      id: "soil",
      name: "土",
      image: "map/img_tile/base_seamless/soil_plain_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassOverSoilPatch: {
      id: "grassOverSoilPatch",
      name: "草かぶせ（土）",
      image: "map/img_tile/grass_over_soil_patch.png",
      passable: true,
      tags: ["overlay", "ground", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeTop: {
      id: "grassEdgeTop",
      name: "草境界・上",
      image: "map/img_tile/grass_edge_top.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeBottom: {
      id: "grassEdgeBottom",
      name: "草境界・下",
      image: "map/img_tile/grass_edge_bottom.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeLeft: {
      id: "grassEdgeLeft",
      name: "草境界・左",
      image: "map/img_tile/grass_edge_left.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeRight: {
      id: "grassEdgeRight",
      name: "草境界・右",
      image: "map/img_tile/grass_edge_right.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    floor: {
      id: "floor",
      name: "木床",
      image: "map/img_tile/rpg_village_extra/wood_plank_floor_01.png",
      passable: true,
      tags: ["ground", "indoor", "wood"],
    },
    wall: {
      id: "wall",
      name: "崖・壁",
      image: "map/img_tile/rpg_village_extra/cliff_wall_01.png",
      passable: false,
      tags: ["terrainBlock", "wall", "block"],
    },
    tree: {
      id: "tree",
      name: "木オブジェクト",
      image: "map/img_tile/rpg_objects/tree_leafy_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    forestWallLeaf: {
      id: "forestWallLeaf",
      name: "森の壁・広葉樹",
      image: "map/img_tile/rpg_village/forest_wall_leaf_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestWallPine: {
      id: "forestWallPine",
      name: "森の壁・針葉樹",
      image: "map/img_tile/rpg_village/forest_wall_pine_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestHedgeOpen: {
      id: "forestHedgeOpen",
      name: "森の入口風",
      image: "map/img_tile/rpg_village/forest_hedge_open_01.png",
      passable: true,
      tags: ["ground", "forest", "nature"],
    },
    shrubCluster: {
      id: "shrubCluster",
      name: "低木群",
      image: "map/img_tile/rpg_objects/bush_01.png",
      passable: false,
      tags: ["object", "bush", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    rock: {
      id: "rock",
      name: "岩オブジェクト",
      image: "map/img_tile/rpg_objects/rock_cluster_01.png",
      passable: false,
      tags: ["object", "rock", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    water: {
      id: "water",
      name: "水辺",
      image: "map/img_tile/base_seamless/water_plain_01.png",
      passable: false,
      tags: ["water", "block"],
    },
    waterShore: {
      id: "waterShore",
      name: "水際",
      image: "map/img_tile/rpg_village/water_shore_01.png",
      passable: false,
      tags: ["water", "shore", "block"],
    },
    flowerMeadow: {
      id: "flowerMeadow",
      name: "花畑草地",
      image: "map/img_tile/rpg_village/flower_meadow_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    darkGrass: {
      id: "darkGrass",
      name: "暗い草地",
      image: "map/img_tile/rpg_village_extra/dark_grass_01.png",
      passable: true,
      tags: ["ground", "grass"],
    },
    wildflowerMeadow: {
      id: "wildflowerMeadow",
      name: "野花の草地",
      image: "map/img_tile/rpg_village_extra/wildflower_meadow_02.png",
      passable: true,
      tags: ["ground", "decoration", "flower"],
    },
    mossyGrass: {
      id: "mossyGrass",
      name: "苔むした草地",
      image: "map/img_tile/rpg_village_extra/mossy_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "moss"],
    },
    wornGrass: {
      id: "wornGrass",
      name: "踏まれた草地",
      image: "map/img_tile/rpg_village_extra/worn_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "blend"],
    },
    cobblestonePath: {
      id: "cobblestonePath",
      name: "丸石道",
      image: "map/img_tile/rpg_village_extra/cobblestone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    crackedStonePath: {
      id: "crackedStonePath",
      name: "ひび割れ石道",
      image: "map/img_tile/rpg_village_extra/cracked_stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    stonePlain: {
      id: "stonePlain",
      name: "Stone plain",
      image: "map/img_tile/base_seamless/stone_plain_01.png",
      passable: true,
      tags: ["ground", "road", "stone", "plain"],
    },
    stonePath: {
      id: "stonePath",
      name: "石道",
      image: "map/img_tile/rpg_village/stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    farmRows: {
      id: "farmRows",
      name: "畑のうね",
      image: "map/img_tile/rpg_village_extra/farm_rows_01.png",
      passable: true,
      tags: ["ground", "farm"],
    },
    sandGround: {
      id: "sandGround",
      name: "砂地",
      image: "map/img_tile/rpg_village_extra/sand_ground_01.png",
      passable: true,
      tags: ["ground", "sand"],
    },
    mudGround: {
      id: "mudGround",
      name: "ぬかるみ",
      image: "map/img_tile/rpg_village_extra/mud_ground_01.png",
      passable: true,
      tags: ["ground", "mud"],
    },
    shallowWater: {
      id: "shallowWater",
      name: "浅瀬",
      image: "map/img_tile/rpg_village_extra/shallow_water_01.png",
      passable: true,
      tags: ["ground", "water", "shallow"],
    },
    marshGrass: {
      id: "marshGrass",
      name: "湿地草",
      image: "map/img_tile/rpg_village_extra/marsh_grass_01.png",
      passable: true,
      tags: ["ground", "marsh"],
    },
    cliffTopGrass: {
      id: "cliffTopGrass",
      name: "崖上草地",
      image: "map/img_tile/rpg_village_extra/cliff_top_grass_01.png",
      passable: true,
      tags: ["ground", "cliff"],
    },
    forestShadowGround: {
      id: "forestShadowGround",
      name: "森影の地面",
      image: "map/img_tile/rpg_village_extra/forest_shadow_ground_01.png",
      passable: true,
      tags: ["ground", "forest", "shadow"],
    },
    plazaEarth: {
      id: "plazaEarth",
      name: "広場の土",
      image: "map/img_tile/rpg_village_extra/plaza_earth_01.png",
      passable: true,
      tags: ["ground", "road", "village"],
    },
    pineTree: {
      id: "pineTree",
      name: "針葉樹オブジェクト",
      image: "map/img_tile/rpg_objects/tree_pine_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    flowerPatchObject: {
      id: "flowerPatchObject",
      name: "花かざり",
      image: "map/img_tile/rpg_objects/flower_patch_01.png",
      passable: true,
      tags: ["object", "decoration", "flower"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stump: {
      id: "stump",
      name: "切り株",
      image: "map/img_tile/rpg_objects/stump_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fallenLog: {
      id: "fallenLog",
      name: "倒木",
      image: "map/img_tile/rpg_objects/fallen_log_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    weeds: {
      id: "weeds",
      name: "草むら飾り",
      image: "map/img_tile/rpg_objects/weeds_01.png",
      passable: true,
      tags: ["object", "decoration", "grass"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fence: {
      id: "fence",
      name: "柵",
      image: "map/img_tile/rpg_objects/fence_01.png",
      passable: false,
      tags: ["object", "fence", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    crate: {
      id: "crate",
      name: "木箱",
      image: "map/img_tile/rpg_objects/crate_01.png",
      passable: false,
      tags: ["object", "box", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    barrel: {
      id: "barrel",
      name: "樽",
      image: "map/img_tile/rpg_objects/barrel_01.png",
      passable: false,
      tags: ["object", "barrel", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    well: {
      id: "well",
      name: "井戸",
      image: "map/img_tile/rpg_objects/well_01.png",
      passable: false,
      tags: ["object", "well", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    lampPost: {
      id: "lampPost",
      name: "街灯",
      image: "map/img_tile/rpg_objects/lamp_post_01.png",
      passable: false,
      tags: ["object", "lamp", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stoneMarker: {
      id: "stoneMarker",
      name: "石碑",
      image: "map/img_tile/rpg_objects/stone_marker_01.png",
      passable: false,
      tags: ["object", "stone", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    bridgePlank: {
      id: "bridgePlank",
      name: "木橋",
      image: "map/img_tile/rpg_objects/bridge_plank_01.png",
      passable: true,
      tags: ["object", "bridge", "wood"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -24,
    },
    door: {
      id: "door",
      name: "入口",
      image: null,
      passable: true,
      tags: ["event", "door"],
    },
    sign: {
      id: "sign",
      name: "看板",
      image: "map/img_tile/rpg_objects/signpost_01.png",
      passable: false,
      tags: ["object", "event", "decoration", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    armorShopFront: {
      id: "armorShopFront",
      name: "防具屋",
      image: "map/img_tile/town_objects_front/armor_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "armor", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    weaponShopFront: {
      id: "weaponShopFront",
      name: "武器屋",
      image: "map/img_tile/town_objects_front/weapon_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "weapon", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    innFront: {
      id: "innFront",
      name: "宿屋",
      image: "map/img_tile/town_objects_front/inn_front_3x2.png",
      passable: false,
      tags: ["object", "building", "inn", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    requestOfficeFront: {
      id: "requestOfficeFront",
      name: "依頼所",
      image: "map/img_tile/town_objects_front/request_office_front_3x2.png",
      passable: false,
      tags: ["object", "building", "requestOffice", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    itemShopFront: {
      id: "itemShopFront",
      name: "アイテム屋",
      image: "map/img_tile/town_objects_front/item_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "item", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
  };

  window.HEALER_TILE_MAPS = {
    // Template only. Copy this when adding a new map.
    template: {
      id: "template",
      name: "タイルマップ雛形",
      tileSize: 48,
      width: 0,
      height: 0,
      defaultTile: "grass",
      layers: [
        { id: "ground", name: "地面", tiles: [] },
        { id: "object", name: "配置物", tiles: [] },
        { id: "event", name: "イベント", tiles: [] },
      ],
      events: [],
    },

    forestTest01: {
      id: "forestTest01",
      name: "森テスト01",
      tileSize: 48,
      width: 12,
      height: 8,
      defaultTile: "grass",
      layers: [
        {
          id: "ground",
          name: "地面",
          tiles: [
            "grass", "grass", "grass", "grass", "road", "road", "grass", "grass", "grass", "grass", "grass", "grass",
            "grass", "grass", "grass", "road", "road", "road", "road", "grass", "grass", "grass", "grass", "grass",
            "grass", "grass", "road", "road", "grass", "grass", "road", "road", "grass", "grass", "grass", "grass",
            "grass", "road", "road", "grass", "grass", "grass", "grass", "road", "road", "grass", "grass", "grass",
            "grass", "road", "grass", "grass", "grass", "soil", "soil", "grass", "road", "grass", "grass", "grass",
            "grass", "road", "road", "grass", "soil", "soil", "soil", "grass", "road", "road", "grass", "grass",
            "grass", "grass", "road", "road", "grass", "grass", "grass", "road", "road", "grass", "grass", "grass",
            "grass", "grass", "grass", "road", "road", "road", "road", "road", "grass", "grass", "grass", "grass",
          ],
        },
        {
          id: "object",
          name: "配置物",
          tiles: [
            "tree", null, null, null, null, null, null, null, null, "tree", "tree", "tree",
            null, null, "tree", null, null, null, null, null, null, null, "rock", null,
            null, null, null, null, null, "water", "water", null, null, null, null, null,
            "tree", null, null, null, null, "water", "water", null, null, null, null, "tree",
            "tree", null, null, null, null, null, null, null, null, null, null, "tree",
            null, null, null, "rock", null, null, null, null, null, null, null, null,
            null, "tree", null, null, null, null, null, null, null, "sign", null, null,
            "tree", "tree", null, null, null, null, null, null, null, null, "tree", "tree",
          ],
        },
        {
          id: "event",
          name: "イベント",
          tiles: [
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, "sign", null, null,
            null, null, null, null, null, "door", "door", null, null, null, null, null,
          ],
        },
      ],
      events: [
        {
          id: "forest_exit",
          name: "森の出口",
          type: "door",
          x: 5,
          y: 7,
          width: 2,
          height: 1,
          targetMap: null,
        },
        {
          id: "forest_sign",
          name: "森の看板",
          type: "inspect",
          x: 9,
          y: 6,
          text: "この先、森の奥。",
        },
      ],
    },

    tileShowcase01: {
      id: "tileShowcase01",
      name: "タイル確認01",
      tileSize: 48,
      width: 8,
      height: 6,
      defaultTile: "grass",
      layers: [
        {
          id: "ground",
          name: "地面",
          tiles: [
            "grass", "grassFlower", "grassDeep", "darkGrass", "wildflowerMeadow", "mossyGrass", "wornGrass", "grassPatchySoil",
            "road", "dirtGrassBlend", "dirtPathLeft", "soil", "cobblestonePath", "crackedStonePath", "stonePath", "plazaEarth",
            "floor", "farmRows", "sandGround", "mudGround", "shallowWater", "marshGrass", "water", "waterShore",
            "cliffTopGrass", "forestShadowGround", "grass", "grass", "grass", "grass", "grass", "grass",
            "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
            "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
          ],
        },
        {
          id: "terrain",
          name: "地形ブロック",
          tiles: [
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            "forestWallLeaf", "forestWallPine", "wall", null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
          ],
        },
        {
          id: "object",
          name: "配置物",
          tiles: [
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            "tree", "pineTree", "shrubCluster", "flowerPatchObject", "rock", "stump", "fallenLog", "weeds",
            "sign", "fence", "crate", "barrel", "well", "lampPost", "stoneMarker", "bridgePlank",
          ],
        },
      ],
      events: [],
    },
  };

  const TEXT_GROUND_SYMBOLS = {
    G: "grass",
    g: "grassPlain2",
    D: "grassDeep",
    R: "road",
    S: "soil",
    W: "water",
    K: "stonePlain",
    C: "cobblestonePath",
    M: "mudGround",
    ".": "grass",
    " ": "grass",
  };

  const TEXT_LAYER_SYMBOLS = {
    F: "forestWallLeaf",
    P: "forestWallPine",
    C: "wall",
    T: "tree",
    p: "pineTree",
    B: "shrubCluster",
    O: "rock",
    f: "flowerPatchObject",
    s: "sign",
    L: "fallenLog",
    w: "well",
    l: "lampPost",
    ".": null,
    " ": null,
  };

  function getMaxTextWidth(rowGroups) {
    let width = 0;
    rowGroups.forEach((rows) => {
      (rows || []).forEach((row) => {
        width = Math.max(width, String(row).length);
      });
    });
    return width;
  }

  function getMaxTextHeight(rowGroups) {
    return rowGroups.reduce((height, rows) => Math.max(height, (rows || []).length), 0);
  }

  function rowsToTiles(rows, symbols, width, height, fallbackTile) {
    const tiles = [];

    for (let y = 0; y < height; y += 1) {
      const row = String((rows || [])[y] || "");

      for (let x = 0; x < width; x += 1) {
        const mark = row[x] || " ";
        const hasSymbol = Object.prototype.hasOwnProperty.call(symbols, mark);
        tiles.push(hasSymbol ? symbols[mark] : fallbackTile);
      }
    }

    return tiles;
  }

  function createTextLayoutMap(spec) {
    const groundRows = spec.groundRows || [];
    const terrainRows = spec.terrainRows || [];
    const objectRows = spec.objectRows || [];
    const rowGroups = [groundRows, terrainRows, objectRows];
    const width = spec.width || getMaxTextWidth(rowGroups);
    const height = spec.height || getMaxTextHeight(rowGroups);
    const defaultTile = spec.defaultTile || "grass";
    const groundSymbols = Object.assign({}, TEXT_GROUND_SYMBOLS, spec.groundSymbols || {});
    const layerSymbols = Object.assign({}, TEXT_LAYER_SYMBOLS, spec.layerSymbols || {});

    return {
      id: spec.id,
      name: spec.name,
      tileSize: spec.tileSize || 48,
      width,
      height,
      defaultTile,
      layers: [
        {
          id: "ground",
          name: "Ground",
          tiles: rowsToTiles(groundRows, groundSymbols, width, height, defaultTile),
        },
        {
          id: "terrain",
          name: "Terrain",
          tiles: rowsToTiles(terrainRows, layerSymbols, width, height, null),
        },
        {
          id: "object",
          name: "Object",
          tiles: rowsToTiles(objectRows, layerSymbols, width, height, null),
        },
      ],
      events: spec.events || [],
    };
  }

  window.HEALER_TEXT_TILE_SYMBOLS = {
    ground: TEXT_GROUND_SYMBOLS,
    layer: TEXT_LAYER_SYMBOLS,
  };
  window.HEALER_CREATE_TEXT_LAYOUT_MAP = createTextLayoutMap;

  window.HEALER_TILE_MAPS.textLayoutSample01 = createTextLayoutMap({
    id: "textLayoutSample01",
    name: "Text layout sample 01",
    width: 8,
    height: 15,
    defaultTile: "grass",
    groundRows: [
      "GGgRGGGg",
      "GGGRRGGG",
      "gGGGGRGG",
      "GGGGGRGg",
      "GGSSGRGG",
      "gGSSRRRG",
      "GGGGGGRG",
      "WWGGGGRG",
      "WWgGRRRG",
      "GGGGRGGg",
      "gGGRRGGG",
      "GGGRGGSS",
      "GGGRGGSS",
      "GGGRRGGG",
      "gGGGRGGG",
    ],
    terrainRows: [
      "FF....FF",
      "F......F",
      "........",
      "........",
      "........",
      "........",
      ".......F",
      ".......F",
      ".......F",
      "........",
      "........",
      "........",
      "........",
      "F......F",
      "FF....FF",
    ],
    objectRows: [
      "T......p",
      "........",
      "..B.....",
      "......O.",
      "........",
      "....f...",
      "T.......",
      "........",
      ".....L..",
      "..O.....",
      ".......s",
      "........",
      "....B...",
      "........",
      "p......T",
    ],
  });

  window.HEALER_TILE_MAPS.startTown01 = {
    id: "startTown01",
    name: "始まりの町01",
    tileSize: 48,
    width: 15,
    height: 8,
    defaultTile: "grass",
    layers: [
      {
        id: "ground",
        name: "Ground",
        tiles: [
          "cobblestonePath", "cobblestonePath", "grass", "grass", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "grass", "grass", "cobblestonePath", "cobblestonePath",
          "cobblestonePath", "cobblestonePath", "cobblestonePath", "grass", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "grass", "cobblestonePath", "cobblestonePath", "cobblestonePath",
          "grass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "grassPlain2",
          "grass", "grass", "cobblestonePath", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "cobblestonePath", "grass", "grass",
          "grass", "grass", "cobblestonePath", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "plazaEarth", "cobblestonePath", "grass", "grass",
          "grass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "grass",
          "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "grass", "grass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "grass", "grass", "grass", "cobblestonePath", "cobblestonePath", "cobblestonePath",
          "cobblestonePath", "cobblestonePath", "grass", "grass", "grass", "grass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "grass", "grass", "grass", "grass", "cobblestonePath", "cobblestonePath",
        ],
      },
      {
        id: "terrain",
        name: "Terrain",
        tiles: [
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
        ],
      },
      {
        id: "object",
        name: "Object",
        tiles: [
          null, null, null, null, "armorShopFront", null, null, null, "weaponShopFront", null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, "innFront", null, null, "requestOfficeFront", null, null, "itemShopFront", null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
        ],
      },
      {
        id: "event",
        name: "イベント",
        tiles: [
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
        ],
      },
    ],
    events: [
      {
        id: "start_town_armor_shop_area",
        name: "防具屋",
        type: "buildingArea",
        x: 4,
        y: 0,
        width: 3,
        height: 2,
        tileId: "armorShopFront",
      },
      {
        id: "start_town_weapon_shop_area",
        name: "武器屋",
        type: "buildingArea",
        x: 8,
        y: 0,
        width: 3,
        height: 2,
        tileId: "weaponShopFront",
      },
      {
        id: "start_town_inn_area",
        name: "宿屋",
        type: "buildingArea",
        x: 3,
        y: 3,
        width: 3,
        height: 2,
        tileId: "innFront",
      },
      {
        id: "start_town_request_office_area",
        name: "依頼所",
        type: "buildingArea",
        x: 6,
        y: 3,
        width: 3,
        height: 2,
        tileId: "requestOfficeFront",
      },
      {
        id: "start_town_item_shop_area",
        name: "アイテム屋",
        type: "buildingArea",
        x: 9,
        y: 3,
        width: 3,
        height: 2,
        tileId: "itemShopFront",
      },
    ],
  };
})();












