(() => {
  "use strict";

  // Map data edited by map collaborators.
  // Tile images are optional for now. When assets are ready, set image to a path
  // such as "map/img_tile/forest/grass.png".
  window.HEALER_TILE_DEFS = {
    test_grass: {
      id: "test_grass",
      name: "テスト",
      image: "map/img_tile/rpg_village/grass_base_01.png",
      passable: true,
      tags: ["ground"],
    },
    grass: {
      id: "grass",
      name: "草地",
      image: "map/img_tile/base_seamless/grass_plain_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassPlain2: {
      id: "grassPlain2",
      name: "草地2",
      image: "map/img_tile/base_seamless/grass_plain_02.png",
      passable: true,
      tags: ["ground", "grass", "plain"],
    },
    grassFlower: {
      id: "grassFlower",
      name: "花の草地",
      image: "map/img_tile/rpg_village/grass_flower_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    grassBase: {
      id: "grassBase",
      name: "草地 ベース",
      image: "map/img_tile/rpg_village/grass_base_01.png",
      passable: true,
      tags: ["ground", "grass", "plain"],
    },
    grassDeep: {
      id: "grassDeep",
      name: "濃い草地",
      image: "map/img_tile/base_seamless/grass_dark_plain_01.png",
      passable: true,
      tags: ["ground", "deepGrass"],
    },
    grassPatchySoil: {
      id: "grassPatchySoil",
      name: "土まじりの草地",
      image: "map/img_tile/rpg_village/grass_patchy_soil_01.png",
      passable: true,
      tags: ["ground", "blend"],
    },
    road: {
      id: "road",
      name: "道",
      image: "map/img_tile/base_seamless/road_plain_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    dirtGrassBlend: {
      id: "dirtGrassBlend",
      name: "土と草の境目",
      image: "map/img_tile/rpg_village/dirt_grass_blend_01.png",
      passable: true,
      tags: ["ground", "road", "blend"],
    },
    dirtPathCenter: {
      id: "dirtPathCenter",
      name: "土の道 中央",
      image: "map/img_tile/rpg_village/dirt_path_center_01.png",
      passable: true,
      tags: ["ground", "road", "dirt"],
    },
    dirtPathDetail: {
      id: "dirtPathDetail",
      name: "土の道 模様",
      image: "map/img_tile/rpg_village/dirt_path_detail_01.png",
      passable: true,
      tags: ["ground", "road", "dirt", "decoration"],
    },
    dirtPathLeft: {
      id: "dirtPathLeft",
      name: "土の道 左寄せ",
      image: "map/img_tile/rpg_village/dirt_path_left_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    soil: {
      id: "soil",
      name: "土",
      image: "map/img_tile/base_seamless/soil_plain_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassOverSoilPatch: {
      id: "grassOverSoilPatch",
      name: "草かぶせ土",
      image: "map/img_tile/grass_over_soil_patch.png",
      passable: true,
      tags: ["overlay", "ground", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeTop: {
      id: "grassEdgeTop",
      name: "草境界 上",
      image: "map/img_tile/grass_edge_top.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeBottom: {
      id: "grassEdgeBottom",
      name: "草境界 下",
      image: "map/img_tile/grass_edge_bottom.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeLeft: {
      id: "grassEdgeLeft",
      name: "草境界 左",
      image: "map/img_tile/grass_edge_left.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeRight: {
      id: "grassEdgeRight",
      name: "草境界 右",
      image: "map/img_tile/grass_edge_right.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    floor: {
      id: "floor",
      name: "木の床",
      image: "map/img_tile/rpg_village_extra/wood_plank_floor_01.png",
      passable: true,
      tags: ["ground", "indoor", "wood"],
    },
    wall: {
      id: "wall",
      name: "崖の壁",
      image: "map/img_tile/rpg_village_extra/cliff_wall_01.png",
      passable: false,
      tags: ["terrainBlock", "wall", "block"],
    },
    tree: {
      id: "tree",
      name: "広葉樹",
      image: "map/img_tile/rpg_objects/tree_leafy_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    forestWallLeaf: {
      id: "forestWallLeaf",
      name: "森の壁 葉",
      image: "map/img_tile/rpg_village/forest_wall_leaf_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestWallPine: {
      id: "forestWallPine",
      name: "森の壁 松",
      image: "map/img_tile/rpg_village/forest_wall_pine_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestHedgeOpen: {
      id: "forestHedgeOpen",
      name: "森の入口",
      image: "map/img_tile/rpg_village/forest_hedge_open_01.png",
      passable: true,
      tags: ["ground", "forest", "nature"],
    },
    shrubCluster: {
      id: "shrubCluster",
      name: "低木",
      image: "map/img_tile/rpg_objects/bush_01.png",
      passable: false,
      tags: ["object", "bush", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    villageShrubCluster: {
      id: "villageShrubCluster",
      name: "茂み",
      image: "map/img_tile/rpg_village/shrub_cluster_01.png",
      passable: false,
      tags: ["terrainBlock", "bush", "block", "nature"],
    },
    rock: {
      id: "rock",
      name: "岩",
      image: "map/img_tile/rpg_objects/rock_cluster_01.png",
      passable: false,
      tags: ["object", "rock", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    water: {
      id: "water",
      name: "水",
      image: "map/img_tile/base_seamless/water_plain_01.png",
      passable: false,
      tags: ["water", "block"],
    },
    waterDeep: {
      id: "waterDeep",
      name: "深い水",
      image: "map/img_tile/rpg_village/water_deep_01.png",
      passable: false,
      tags: ["water", "deep", "block"],
    },
    waterShore: {
      id: "waterShore",
      name: "水辺",
      image: "map/img_tile/rpg_village/water_shore_01.png",
      passable: false,
      tags: ["water", "shore", "block"],
    },
    flowerMeadow: {
      id: "flowerMeadow",
      name: "花畑",
      image: "map/img_tile/rpg_village/flower_meadow_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    darkGrass: {
      id: "darkGrass",
      name: "暗い草地",
      image: "map/img_tile/rpg_village_extra/dark_grass_01.png",
      passable: true,
      tags: ["ground", "grass"],
    },
    wildflowerMeadow: {
      id: "wildflowerMeadow",
      name: "野花の草地",
      image: "map/img_tile/rpg_village_extra/wildflower_meadow_02.png",
      passable: true,
      tags: ["ground", "decoration", "flower"],
    },
    mossyGrass: {
      id: "mossyGrass",
      name: "苔の草地",
      image: "map/img_tile/rpg_village_extra/mossy_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "moss"],
    },
    wornGrass: {
      id: "wornGrass",
      name: "すり減った草地",
      image: "map/img_tile/rpg_village_extra/worn_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "blend"],
    },
    cobblestonePath: {
      id: "cobblestonePath",
      name: "石畳",
      image: "map/img_tile/rpg_village_extra/cobblestone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    crackedStonePath: {
      id: "crackedStonePath",
      name: "ひび割れ石道",
      image: "map/img_tile/rpg_village_extra/cracked_stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    stonePlain: {
      id: "stonePlain",
      name: "石地面",
      image: "map/img_tile/base_seamless/stone_plain_01.png",
      passable: true,
      tags: ["ground", "road", "stone", "plain"],
    },
    stonePath: {
      id: "stonePath",
      name: "石の道",
      image: "map/img_tile/rpg_village/stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    farmRows: {
      id: "farmRows",
      name: "畑",
      image: "map/img_tile/rpg_village_extra/farm_rows_01.png",
      passable: true,
      tags: ["ground", "farm"],
    },
    sandGround: {
      id: "sandGround",
      name: "砂地",
      image: "map/img_tile/rpg_village_extra/sand_ground_01.png",
      passable: true,
      tags: ["ground", "sand"],
    },
    mudGround: {
      id: "mudGround",
      name: "泥地",
      image: "map/img_tile/rpg_village_extra/mud_ground_01.png",
      passable: true,
      tags: ["ground", "mud"],
    },
    shallowWater: {
      id: "shallowWater",
      name: "浅瀬",
      image: "map/img_tile/rpg_village_extra/shallow_water_01.png",
      passable: true,
      tags: ["ground", "water", "shallow"],
    },
    marshGrass: {
      id: "marshGrass",
      name: "湿地草",
      image: "map/img_tile/rpg_village_extra/marsh_grass_01.png",
      passable: true,
      tags: ["ground", "marsh"],
    },
    cliffTopGrass: {
      id: "cliffTopGrass",
      name: "崖上草地",
      image: "map/img_tile/rpg_village_extra/cliff_top_grass_01.png",
      passable: true,
      tags: ["ground", "cliff"],
    },
    forestShadowGround: {
      id: "forestShadowGround",
      name: "森の影",
      image: "map/img_tile/rpg_village_extra/forest_shadow_ground_01.png",
      passable: true,
      tags: ["ground", "forest", "shadow"],
    },
    plazaEarth: {
      id: "plazaEarth",
      name: "広場の土",
      image: "map/img_tile/rpg_village_extra/plaza_earth_01.png",
      passable: true,
      tags: ["ground", "road", "village"],
    },
    pineTree: {
      id: "pineTree",
      name: "松",
      image: "map/img_tile/rpg_objects/tree_pine_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    flowerPatchObject: {
      id: "flowerPatchObject",
      name: "花壇",
      image: "map/img_tile/rpg_objects/flower_patch_01.png",
      passable: true,
      tags: ["object", "decoration", "flower"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stump: {
      id: "stump",
      name: "切り株",
      image: "map/img_tile/rpg_objects/stump_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fallenLog: {
      id: "fallenLog",
      name: "倒木",
      image: "map/img_tile/rpg_objects/fallen_log_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    weeds: {
      id: "weeds",
      name: "雑草",
      image: "map/img_tile/rpg_objects/weeds_01.png",
      passable: true,
      tags: ["object", "decoration", "grass"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fence: {
      id: "fence",
      name: "柵",
      image: "map/img_tile/rpg_objects/fence_01.png",
      passable: false,
      tags: ["object", "fence", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    crate: {
      id: "crate",
      name: "木箱",
      image: "map/img_tile/rpg_objects/crate_01.png",
      passable: false,
      tags: ["object", "box", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    barrel: {
      id: "barrel",
      name: "樽",
      image: "map/img_tile/rpg_objects/barrel_01.png",
      passable: false,
      tags: ["object", "barrel", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    well: {
      id: "well",
      name: "井戸",
      image: "map/img_tile/rpg_objects/well_01.png",
      passable: false,
      tags: ["object", "well", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    lampPost: {
      id: "lampPost",
      name: "街灯",
      image: "map/img_tile/rpg_objects/lamp_post_01.png",
      passable: false,
      tags: ["object", "lamp", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stoneMarker: {
      id: "stoneMarker",
      name: "石碑",
      image: "map/img_tile/rpg_objects/stone_marker_01.png",
      passable: false,
      tags: ["object", "stone", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    bridgePlank: {
      id: "bridgePlank",
      name: "木の橋",
      image: "map/img_tile/rpg_objects/bridge_plank_01.png",
      passable: true,
      tags: ["object", "bridge", "wood"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -24,
    },
    door: {
      id: "door",
      name: "出入口",
      image: null,
      passable: true,
      tags: ["event", "door"],
    },
    sign: {
      id: "sign",
      name: "看板",
      image: "map/img_tile/rpg_objects/signpost_01.png",
      passable: false,
      tags: ["object", "event", "decoration", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    armorShopFront: {
      id: "armorShopFront",
      name: "防具屋",
      image: "map/img_tile/town_objects_front/armor_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "armor", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    weaponShopFront: {
      id: "weaponShopFront",
      name: "武器屋",
      image: "map/img_tile/town_objects_front/weapon_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "weapon", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    innFront: {
      id: "innFront",
      name: "宿屋",
      image: "map/img_tile/town_objects_front/inn_front_3x2.png",
      passable: false,
      tags: ["object", "building", "inn", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    requestOfficeFront: {
      id: "requestOfficeFront",
      name: "依頼所",
      image: "map/img_tile/town_objects_front/request_office_front_3x2.png",
      passable: false,
      tags: ["object", "building", "requestOffice", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    itemShopFront: {
      id: "itemShopFront",
      name: "アイテム屋",
      image: "map/img_tile/town_objects_front/item_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "item", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    townHouseFront: {
      id: "townHouseFront",
      name: "町の民家 正面",
      image: "map/img_tile/town_objects_front/town_house_front_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    townHouseSideLeft: {
      id: "townHouseSideLeft",
      name: "町の民家 左向き",
      image: "map/img_tile/town_objects_front/town_house_side_left_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    townHouseSideRight: {
      id: "townHouseSideRight",
      name: "町の民家 右向き",
      image: "map/img_tile/town_objects_front/town_house_side_right_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    // Generated ground tiles created from the 2026-07-15 draft sheets.
    cityTile01: {
      id: "cityTile01",
      name: "都市タイル 明るい石畳",
      image: "map/img_tile/generated_ground/city_generated/tile_01_01.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile02: {
      id: "cityTile02",
      name: "都市タイル 暗い石畳",
      image: "map/img_tile/generated_ground/city_generated/tile_01_02.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile03: {
      id: "cityTile03",
      name: "都市タイル 整った敷石",
      image: "map/img_tile/generated_ground/city_generated/tile_01_03.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile04: {
      id: "cityTile04",
      name: "都市タイル 紋章広場",
      image: "map/img_tile/generated_ground/city_generated/tile_01_04.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile05: {
      id: "cityTile05",
      name: "都市タイル 赤レンガ",
      image: "map/img_tile/generated_ground/city_generated/tile_02_01.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile06: {
      id: "cityTile06",
      name: "都市タイル 斜めレンガ",
      image: "map/img_tile/generated_ground/city_generated/tile_02_02.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile07: {
      id: "cityTile07",
      name: "都市タイル 古い石畳",
      image: "map/img_tile/generated_ground/city_generated/tile_02_03.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile08: {
      id: "cityTile08",
      name: "都市タイル 大判石床",
      image: "map/img_tile/generated_ground/city_generated/tile_02_04.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile09: {
      id: "cityTile09",
      name: "都市タイル 縁石道路",
      image: "map/img_tile/generated_ground/city_generated/tile_03_01.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile10: {
      id: "cityTile10",
      name: "都市タイル 角縁石道路",
      image: "map/img_tile/generated_ground/city_generated/tile_03_02.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile11: {
      id: "cityTile11",
      name: "都市タイル 水路",
      image: "map/img_tile/generated_ground/city_generated/tile_03_03.png",
      passable: false,
      tags: ["ground", "generated", "city"],
    },
    cityTile12: {
      id: "cityTile12",
      name: "都市タイル 水路角",
      image: "map/img_tile/generated_ground/city_generated/tile_03_04.png",
      passable: false,
      tags: ["ground", "generated", "city"],
    },
    cityTile13: {
      id: "cityTile13",
      name: "都市タイル 通路石床",
      image: "map/img_tile/generated_ground/city_generated/tile_04_01.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile14: {
      id: "cityTile14",
      name: "都市タイル 赤い屋根",
      image: "map/img_tile/generated_ground/city_generated/tile_04_02.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile15: {
      id: "cityTile15",
      name: "都市タイル 青い屋根",
      image: "map/img_tile/generated_ground/city_generated/tile_04_03.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    cityTile16: {
      id: "cityTile16",
      name: "都市タイル 白い装飾床",
      image: "map/img_tile/generated_ground/city_generated/tile_04_04.png",
      passable: true,
      tags: ["ground", "generated", "city"],
    },
    townTile01: {
      id: "townTile01",
      name: "街タイル 01",
      image: "map/img_tile/generated_ground/town_generated/tile_01_01.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile02: {
      id: "townTile02",
      name: "街タイル 02",
      image: "map/img_tile/generated_ground/town_generated/tile_01_02.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile03: {
      id: "townTile03",
      name: "街タイル 03",
      image: "map/img_tile/generated_ground/town_generated/tile_01_03.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile04: {
      id: "townTile04",
      name: "街タイル 04",
      image: "map/img_tile/generated_ground/town_generated/tile_01_04.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile05: {
      id: "townTile05",
      name: "街タイル 05",
      image: "map/img_tile/generated_ground/town_generated/tile_02_01.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile06: {
      id: "townTile06",
      name: "街タイル 06",
      image: "map/img_tile/generated_ground/town_generated/tile_02_02.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile07: {
      id: "townTile07",
      name: "街タイル 07",
      image: "map/img_tile/generated_ground/town_generated/tile_02_03.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile08: {
      id: "townTile08",
      name: "街タイル 08",
      image: "map/img_tile/generated_ground/town_generated/tile_02_04.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile09: {
      id: "townTile09",
      name: "街タイル 09",
      image: "map/img_tile/generated_ground/town_generated/tile_03_01.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile10: {
      id: "townTile10",
      name: "街タイル 10",
      image: "map/img_tile/generated_ground/town_generated/tile_03_02.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile11: {
      id: "townTile11",
      name: "街タイル 11",
      image: "map/img_tile/generated_ground/town_generated/tile_03_03.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile12: {
      id: "townTile12",
      name: "街タイル 12",
      image: "map/img_tile/generated_ground/town_generated/tile_03_04.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile13: {
      id: "townTile13",
      name: "街タイル 13",
      image: "map/img_tile/generated_ground/town_generated/tile_04_01.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile14: {
      id: "townTile14",
      name: "街タイル 14",
      image: "map/img_tile/generated_ground/town_generated/tile_04_02.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile15: {
      id: "townTile15",
      name: "街タイル 15",
      image: "map/img_tile/generated_ground/town_generated/tile_04_03.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    townTile16: {
      id: "townTile16",
      name: "街タイル 16",
      image: "map/img_tile/generated_ground/town_generated/tile_04_04.png",
      passable: true,
      tags: ["ground", "generated", "town"],
    },
    villageTile01: {
      id: "villageTile01",
      name: "村タイル 01",
      image: "map/img_tile/generated_ground/village_generated/tile_01_01.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile02: {
      id: "villageTile02",
      name: "村タイル 02",
      image: "map/img_tile/generated_ground/village_generated/tile_01_02.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile03: {
      id: "villageTile03",
      name: "村タイル 03",
      image: "map/img_tile/generated_ground/village_generated/tile_01_03.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile04: {
      id: "villageTile04",
      name: "村タイル 04",
      image: "map/img_tile/generated_ground/village_generated/tile_01_04.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile05: {
      id: "villageTile05",
      name: "村タイル 05",
      image: "map/img_tile/generated_ground/village_generated/tile_02_01.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile06: {
      id: "villageTile06",
      name: "村タイル 06",
      image: "map/img_tile/generated_ground/village_generated/tile_02_02.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile07: {
      id: "villageTile07",
      name: "村タイル 07",
      image: "map/img_tile/generated_ground/village_generated/tile_02_03.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile08: {
      id: "villageTile08",
      name: "村タイル 08",
      image: "map/img_tile/generated_ground/village_generated/tile_02_04.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile09: {
      id: "villageTile09",
      name: "村タイル 09",
      image: "map/img_tile/generated_ground/village_generated/tile_03_01.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile10: {
      id: "villageTile10",
      name: "村タイル 10",
      image: "map/img_tile/generated_ground/village_generated/tile_03_02.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile11: {
      id: "villageTile11",
      name: "村タイル 11",
      image: "map/img_tile/generated_ground/village_generated/tile_03_03.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile12: {
      id: "villageTile12",
      name: "村タイル 12",
      image: "map/img_tile/generated_ground/village_generated/tile_03_04.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile13: {
      id: "villageTile13",
      name: "村タイル 13",
      image: "map/img_tile/generated_ground/village_generated/tile_04_01.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile14: {
      id: "villageTile14",
      name: "村タイル 14",
      image: "map/img_tile/generated_ground/village_generated/tile_04_02.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile15: {
      id: "villageTile15",
      name: "村タイル 15",
      image: "map/img_tile/generated_ground/village_generated/tile_04_03.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    villageTile16: {
      id: "villageTile16",
      name: "村タイル 16",
      image: "map/img_tile/generated_ground/village_generated/tile_04_04.png",
      passable: true,
      tags: ["ground", "generated", "village"],
    },
    fieldTile01: {
      id: "fieldTile01",
      name: "自然タイル 01",
      image: "map/img_tile/generated_ground/field_generated/tile_01_01.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile02: {
      id: "fieldTile02",
      name: "自然タイル 02",
      image: "map/img_tile/generated_ground/field_generated/tile_01_02.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile03: {
      id: "fieldTile03",
      name: "自然タイル 03",
      image: "map/img_tile/generated_ground/field_generated/tile_01_03.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile04: {
      id: "fieldTile04",
      name: "自然タイル 04",
      image: "map/img_tile/generated_ground/field_generated/tile_01_04.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile05: {
      id: "fieldTile05",
      name: "自然タイル 05",
      image: "map/img_tile/generated_ground/field_generated/tile_02_01.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile06: {
      id: "fieldTile06",
      name: "自然タイル 06",
      image: "map/img_tile/generated_ground/field_generated/tile_02_02.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile07: {
      id: "fieldTile07",
      name: "自然タイル 07",
      image: "map/img_tile/generated_ground/field_generated/tile_02_03.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile08: {
      id: "fieldTile08",
      name: "自然タイル 08",
      image: "map/img_tile/generated_ground/field_generated/tile_02_04.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile09: {
      id: "fieldTile09",
      name: "自然タイル 09",
      image: "map/img_tile/generated_ground/field_generated/tile_03_01.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile10: {
      id: "fieldTile10",
      name: "自然タイル 10",
      image: "map/img_tile/generated_ground/field_generated/tile_03_02.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile11: {
      id: "fieldTile11",
      name: "自然タイル 11",
      image: "map/img_tile/generated_ground/field_generated/tile_03_03.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile12: {
      id: "fieldTile12",
      name: "自然タイル 12",
      image: "map/img_tile/generated_ground/field_generated/tile_03_04.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile13: {
      id: "fieldTile13",
      name: "自然タイル 13",
      image: "map/img_tile/generated_ground/field_generated/tile_04_01.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile14: {
      id: "fieldTile14",
      name: "自然タイル 14",
      image: "map/img_tile/generated_ground/field_generated/tile_04_02.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile15: {
      id: "fieldTile15",
      name: "自然タイル 15",
      image: "map/img_tile/generated_ground/field_generated/tile_04_03.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    fieldTile16: {
      id: "fieldTile16",
      name: "自然タイル 16",
      image: "map/img_tile/generated_ground/field_generated/tile_04_04.png",
      passable: true,
      tags: ["ground", "generated", "field"],
    },
    demonCastleTile01: {
      id: "demonCastleTile01",
      name: "魔王城タイル 01",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_01_01.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile02: {
      id: "demonCastleTile02",
      name: "魔王城タイル 02",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_01_02.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile03: {
      id: "demonCastleTile03",
      name: "魔王城タイル 03",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_01_03.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile04: {
      id: "demonCastleTile04",
      name: "魔王城タイル 04",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_01_04.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile05: {
      id: "demonCastleTile05",
      name: "魔王城タイル 05",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_02_01.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile06: {
      id: "demonCastleTile06",
      name: "魔王城タイル 06",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_02_02.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile07: {
      id: "demonCastleTile07",
      name: "魔王城タイル 07",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_02_03.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile08: {
      id: "demonCastleTile08",
      name: "魔王城タイル 08",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_02_04.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile09: {
      id: "demonCastleTile09",
      name: "魔王城タイル 09",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_03_01.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile10: {
      id: "demonCastleTile10",
      name: "魔王城タイル 10",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_03_02.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile11: {
      id: "demonCastleTile11",
      name: "魔王城タイル 11",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_03_03.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile12: {
      id: "demonCastleTile12",
      name: "魔王城タイル 12",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_03_04.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile13: {
      id: "demonCastleTile13",
      name: "魔王城タイル 13",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_04_01.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile14: {
      id: "demonCastleTile14",
      name: "魔王城タイル 14",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_04_02.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile15: {
      id: "demonCastleTile15",
      name: "魔王城タイル 15",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_04_03.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    demonCastleTile16: {
      id: "demonCastleTile16",
      name: "魔王城タイル 16",
      image: "map/img_tile/generated_ground/demon_castle_generated/tile_04_04.png",
      passable: true,
      tags: ["ground", "generated", "demonCastle"],
    },
    // Generated city facility exteriors.
    cityRequestOfficeFront: {
      id: "cityRequestOfficeFront",
      name: "都市部 依頼所",
      image: "map/img_tile/city_objects_front/city_request_office_front.png",
      passable: false,
      tags: ["object", "building", "requestOffice", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    cityArmorShopFront: {
      id: "cityArmorShopFront",
      name: "都市部 防具屋",
      image: "map/img_tile/city_objects_front/city_armor_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "armor", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    cityInnFront: {
      id: "cityInnFront",
      name: "都市部 宿屋",
      image: "map/img_tile/city_objects_front/city_inn_front.png",
      passable: false,
      tags: ["object", "building", "inn", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    cityWeaponShopFront: {
      id: "cityWeaponShopFront",
      name: "都市部 武器屋",
      image: "map/img_tile/city_objects_front/city_weapon_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "weapon", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
    cityItemShopFront: {
      id: "cityItemShopFront",
      name: "都市部 アイテム屋",
      image: "map/img_tile/city_objects_front/city_item_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "item", "city", "block"],
      drawWidth: 192,
      drawHeight: 240,
      drawOffsetX: 0,
      drawOffsetY: 0,
    },
  };

  window.HEALER_TILE_MAPS = {
    // Template only. Copy this when adding a new map.
    template: {
      id: "template",
      name: "テンプレート",
      tileSize: 48,
      width: 0,
      height: 0,
      defaultTile: "grass",
      layers: [
        { id: "ground", name: "地面", tiles: [] },
        { id: "object", name: "配置物", tiles: [] },
        { id: "event", name: "イベント", tiles: [] },
      ],
      events: [],
    },

    forestTest01: {
      id: "forestTest01",
      name: "森テスト01",
      tileSize: 48,
      width: 15,
      height: 8,
      defaultTile: "grass",
      layers: [
        {
          id: "ground",
          name: "地面",
          tiles: [
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass",
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass",
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass",
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass",
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass",
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass",
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass",
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass",
          ],
        },
        {
          id: "terrain",
          name: "地形",
          tiles: [
            { tileId: "forestWallPine", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            { tileId: "forestWallPine", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            { tileId: "forestWallPine", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            { tileId: "forestWallPine", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            { tileId: "forestWallPine", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            { tileId: "forestWallPine", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
          ],
        },
        {
          id: "object",
          name: "配置物",
          tiles: [
            null, "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree",
          ],
        },
        {
          id: "event",
          name: "イベント",
          tiles: [
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          ],
        },
      ],
      events: [
        {
          id: "forest_exit",
          name: "森の出口",
          type: "door",
          x: 5,
          y: 7,
          width: 2,
          height: 1,
          targetMap: null,
        },
        {
          id: "forest_sign",
          name: "森の看板",
          type: "inspect",
          x: 9,
          y: 6,
          text: "森の奥に注意。",
        },
      ],
    },

    forest2: {
      id: "forest2",
      name: "森テスト02",
      tileSize: 48,
      width: 15,
      height: 8,
      defaultTile: "grass",
      layers: [
        {
          id: "ground",
          name: "地面",
          tiles: [
            { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, "grass", "darkGrass", "darkGrass", "darkGrass", "grass",
            { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, "grass",
            { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 },
            { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, "grass",
            { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, "grass",
            { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 }, { tileId: "darkGrass", rotate: 180 },
            "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", "darkGrass", { tileId: "darkGrass", rotate: 180 },
            "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
          ],
        },
        {
          id: "terrain",
          name: "地形",
          tiles: [
            "forestWallPine", "forestWallPine", "forestWallPine", "forestWallPine", "forestWallPine", "forestWallPine", "forestWallPine", "forestWallPine", "forestWallPine", "forestWallPine", "forestWallPine", null, null, null, { tileId: "forestWallPine", rotate: 90 },
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallPine", rotate: 90 },
            { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 180 }, { tileId: "forestWallPine", rotate: 90 },
          ],
        },
        {
          id: "object",
          name: "配置物",
          tiles: [
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", "pineTree", null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          ],
        },
        {
          id: "event",
          name: "イベント",
          tiles: [
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          ],
        },
      ],
      events: [],
    },

  };

  const TEXT_GROUND_SYMBOLS = {
    G: "grass",
    g: "grassPlain2",
    A: "grassBase",
    D: "grassDeep",
    R: "road",
    r: "dirtPathCenter",
    d: "dirtPathDetail",
    S: "soil",
    W: "water",
    w: "waterDeep",
    K: "stonePlain",
    C: "cobblestonePath",
    M: "mudGround",
    ".": "grass",
    " ": "grass",
  };

  const TEXT_LAYER_SYMBOLS = {
    F: "forestWallLeaf",
    P: "forestWallPine",
    C: "wall",
    T: "tree",
    p: "pineTree",
    B: "shrubCluster",
    O: "rock",
    f: "flowerPatchObject",
    s: "sign",
    L: "fallenLog",
    w: "well",
    l: "lampPost",
    h: "villageShrubCluster",
    H: "townHouseFront",
    Q: "cityRequestOfficeFront",
    A: "cityArmorShopFront",
    N: "cityInnFront",
    V: "cityWeaponShopFront",
    I: "cityItemShopFront",
    ".": null,
    " ": null,
  };

  function getMaxTextWidth(rowGroups) {
    let width = 0;
    rowGroups.forEach((rows) => {
      (rows || []).forEach((row) => {
        width = Math.max(width, String(row).length);
      });
    });
    return width;
  }

  function getMaxTextHeight(rowGroups) {
    return rowGroups.reduce((height, rows) => Math.max(height, (rows || []).length), 0);
  }

  function rowsToTiles(rows, symbols, width, height, fallbackTile) {
    const tiles = [];

    for (let y = 0; y < height; y += 1) {
      const row = String((rows || [])[y] || "");

      for (let x = 0; x < width; x += 1) {
        const mark = row[x] || " ";
        const hasSymbol = Object.prototype.hasOwnProperty.call(symbols, mark);
        tiles.push(hasSymbol ? symbols[mark] : fallbackTile);
      }
    }

    return tiles;
  }

  function createTextLayoutMap(spec) {
    const groundRows = spec.groundRows || [];
    const terrainRows = spec.terrainRows || [];
    const objectRows = spec.objectRows || [];
    const rowGroups = [groundRows, terrainRows, objectRows];
    const width = spec.width || getMaxTextWidth(rowGroups);
    const height = spec.height || getMaxTextHeight(rowGroups);
    const defaultTile = spec.defaultTile || "grass";
    const groundSymbols = Object.assign({}, TEXT_GROUND_SYMBOLS, spec.groundSymbols || {});
    const layerSymbols = Object.assign({}, TEXT_LAYER_SYMBOLS, spec.layerSymbols || {});

    return {
      id: spec.id,
      name: spec.name,
      tileSize: spec.tileSize || 48,
      width,
      height,
      defaultTile,
      layers: [
        {
          id: "ground",
          name: "Ground",
          tiles: rowsToTiles(groundRows, groundSymbols, width, height, defaultTile),
        },
        {
          id: "terrain",
          name: "Terrain",
          tiles: rowsToTiles(terrainRows, layerSymbols, width, height, null),
        },
        {
          id: "object",
          name: "Object",
          tiles: rowsToTiles(objectRows, layerSymbols, width, height, null),
        },
      ],
      events: spec.events || [],
    };
  }

  window.HEALER_TEXT_TILE_SYMBOLS = {
    ground: TEXT_GROUND_SYMBOLS,
    layer: TEXT_LAYER_SYMBOLS,
  };
  window.HEALER_CREATE_TEXT_LAYOUT_MAP = createTextLayoutMap;

  window.HEALER_TILE_MAPS.startTown01 = {
      id: "startTown01",
      name: "始まりの町01",
      tileSize: 48,
      width: 15,
      height: 8,
      defaultTile: "grass",
      layers: [
        {
          id: "ground",
          name: "地面",
          tiles: [
            "mossyGrass", "mossyGrass", "mossyGrass", "mossyGrass", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "mossyGrass", "mossyGrass", "mossyGrass", "mossyGrass",
            "mossyGrass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "cobblestonePath", "cobblestonePath", "cobblestonePath", "mossyGrass",
            "mossyGrass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "mossyGrass",
            "mossyGrass", "cobblestonePath", "cobblestonePath", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "cobblestonePath", "cobblestonePath", "mossyGrass",
            "mossyGrass", "cobblestonePath", "cobblestonePath", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "stonePlain", "cobblestonePath", "cobblestonePath", "mossyGrass",
            "mossyGrass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "mossyGrass",
            "mossyGrass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "mossyGrass",
            "mossyGrass", "mossyGrass", "mossyGrass", "mossyGrass", "mossyGrass", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "cobblestonePath", "mossyGrass", "mossyGrass", "mossyGrass", "mossyGrass", "mossyGrass",
          ],
        },
        {
          id: "terrain",
          name: "地形",
          tiles: [
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          ],
        },
        {
          id: "object",
          name: "配置物",
          tiles: [
            "fence", "fence", "fence", "fence", "armorShopFront", null, null, null, "weaponShopFront", null, null, "fence", "fence", "fence", "fence",
            "flowerPatchObject", null, null, null, null, null, null, null, null, null, null, null, null, null, "flowerPatchObject",
            "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, null, null, "shrubCluster",
            "shrubCluster", null, null, "innFront", null, null, "requestOfficeFront", null, null, "itemShopFront", null, null, null, null, "shrubCluster",
            "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, null, null, "shrubCluster",
            "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, null, null, "shrubCluster",
            "flowerPatchObject", null, null, null, null, null, null, null, null, null, null, null, null, null, "flowerPatchObject",
            "fence", "fence", "fence", "fence", "fence", null, null, null, null, null, "fence", "fence", "fence", "fence", "fence",
          ],
        },
        {
          id: "event",
          name: "イベント",
          tiles: [
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          ],
        }
      ],
      events: [
              {
                      "id": "start_town_armor_shop_area",
                      "name": "防具屋エリア",
                      "type": "buildingArea",
                      "x": 4,
                      "y": 0,
                      "width": 3,
                      "height": 2,
                      "tileId": "armorShopFront"
              },
              {
                      "id": "start_town_weapon_shop_area",
                      "name": "武器屋エリア",
                      "type": "buildingArea",
                      "x": 8,
                      "y": 0,
                      "width": 3,
                      "height": 2,
                      "tileId": "weaponShopFront"
              },
              {
                      "id": "start_town_inn_area",
                      "name": "宿屋エリア",
                      "type": "buildingArea",
                      "x": 3,
                      "y": 3,
                      "width": 3,
                      "height": 2,
                      "tileId": "innFront"
              },
              {
                      "id": "start_town_request_office_area",
                      "name": "依頼所エリア",
                      "type": "buildingArea",
                      "x": 6,
                      "y": 3,
                      "width": 3,
                      "height": 2,
                      "tileId": "requestOfficeFront"
              },
              {
                      "id": "start_town_item_shop_area",
                      "name": "アイテム屋エリア",
                      "type": "buildingArea",
                      "x": 9,
                      "y": 3,
                      "width": 3,
                      "height": 2,
                      "tileId": "itemShopFront"
              }
      ],
    };

  window.HEALER_TILE_MAPS.flower = {
      id: "flower",
      name: "花マップ",
      tileSize: 48,
      width: 15,
      height: 8,
      defaultTile: "grass",
      layers: [
        {
          id: "ground",
          name: "地面",
          tiles: [
            "grass", { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, "grass",
            { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, "grass",
            "grass", { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, "grass",
            "grass", { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, "grass",
            "grass", { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, "grass",
            "grass", { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, "grass",
            "grass", { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, "grass",
            "grass", { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, { tileId: "flowerMeadow", rotate: 270 }, "grass",
          ],
        },
        {
          id: "terrain",
          name: "地形",
          tiles: [
            { tileId: "forestWallLeaf", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallLeaf", rotate: 90 },
            { tileId: "forestWallLeaf", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallLeaf", rotate: 90 },
            { tileId: "forestWallLeaf", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallLeaf", rotate: 90 },
            { tileId: "forestWallLeaf", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallLeaf", rotate: 90 },
            { tileId: "forestWallLeaf", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallLeaf", rotate: 90 },
            { tileId: "forestWallLeaf", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallLeaf", rotate: 90 },
            { tileId: "forestWallLeaf", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallLeaf", rotate: 90 },
            { tileId: "forestWallLeaf", rotate: 270 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { tileId: "forestWallLeaf", rotate: 90 },
          ],
        },
        {
          id: "object",
          name: "配置物",
          tiles: [
            null, "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, "shrubCluster", null,
            null, "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, "shrubCluster", null,
            null, "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, "shrubCluster", null,
            null, "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, "shrubCluster", null,
            null, "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, "shrubCluster", null,
            null, "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, "shrubCluster", null,
            null, "shrubCluster", null, null, null, null, null, null, null, null, null, null, null, "shrubCluster", null,
            null, "shrubCluster", "shrubCluster", "shrubCluster", "shrubCluster", "shrubCluster", null, null, null, "shrubCluster", "shrubCluster", "shrubCluster", "shrubCluster", "shrubCluster", null,
          ],
        },
        {
          id: "event",
          name: "イベント",
          tiles: [
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
          ],
        }
      ],
      events: [],
    };
})();


