(() => {
  "use strict";

  // Map data edited by map collaborators.
  // Tile images are optional for now. When assets are ready, set image to a path
  // such as "map/img_tile/forest/grass.png".
  window.HEALER_TILE_DEFS = {
    grass: {
      id: "grass",
      name: "草地",
      image: "map/img_tile/rpg_village/grass_base_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassFlower: {
      id: "grassFlower",
      name: "花つき草地",
      image: "map/img_tile/rpg_village/grass_flower_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    grassDeep: {
      id: "grassDeep",
      name: "濃い草地",
      image: "map/img_tile/rpg_village/grass_deep_01.png",
      passable: true,
      tags: ["ground", "deepGrass"],
    },
    grassPatchySoil: {
      id: "grassPatchySoil",
      name: "土まじり草地",
      image: "map/img_tile/rpg_village/grass_patchy_soil_01.png",
      passable: true,
      tags: ["ground", "blend"],
    },
    road: {
      id: "road",
      name: "道",
      image: "map/img_tile/rpg_village/dirt_path_center_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    dirtGrassBlend: {
      id: "dirtGrassBlend",
      name: "草土なじみ",
      image: "map/img_tile/rpg_village/dirt_grass_blend_01.png",
      passable: true,
      tags: ["ground", "road", "blend"],
    },
    dirtPathLeft: {
      id: "dirtPathLeft",
      name: "土道・端",
      image: "map/img_tile/rpg_village/dirt_path_left_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    soil: {
      id: "soil",
      name: "土",
      image: "map/img_tile/rpg_village/dirt_path_detail_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassOverSoilPatch: {
      id: "grassOverSoilPatch",
      name: "草かぶせ（土）",
      image: "map/img_tile/grass_over_soil_patch.png",
      passable: true,
      tags: ["overlay", "ground", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeTop: {
      id: "grassEdgeTop",
      name: "草境界・上",
      image: "map/img_tile/grass_edge_top.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeBottom: {
      id: "grassEdgeBottom",
      name: "草境界・下",
      image: "map/img_tile/grass_edge_bottom.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeLeft: {
      id: "grassEdgeLeft",
      name: "草境界・左",
      image: "map/img_tile/grass_edge_left.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeRight: {
      id: "grassEdgeRight",
      name: "草境界・右",
      image: "map/img_tile/grass_edge_right.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    floor: {
      id: "floor",
      name: "木床",
      image: "map/img_tile/rpg_village_extra/wood_plank_floor_01.png",
      passable: true,
      tags: ["ground", "indoor", "wood"],
    },
    wall: {
      id: "wall",
      name: "崖・壁",
      image: "map/img_tile/rpg_village_extra/cliff_wall_01.png",
      passable: false,
      tags: ["terrainBlock", "wall", "block"],
    },
    tree: {
      id: "tree",
      name: "木オブジェクト",
      image: "map/img_tile/rpg_objects/tree_leafy_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    forestWallLeaf: {
      id: "forestWallLeaf",
      name: "森の壁・広葉樹",
      image: "map/img_tile/rpg_village/forest_wall_leaf_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestWallPine: {
      id: "forestWallPine",
      name: "森の壁・針葉樹",
      image: "map/img_tile/rpg_village/forest_wall_pine_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestHedgeOpen: {
      id: "forestHedgeOpen",
      name: "森の入口風",
      image: "map/img_tile/rpg_village/forest_hedge_open_01.png",
      passable: true,
      tags: ["ground", "forest", "nature"],
    },
    shrubCluster: {
      id: "shrubCluster",
      name: "低木群",
      image: "map/img_tile/rpg_objects/bush_01.png",
      passable: false,
      tags: ["object", "bush", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    rock: {
      id: "rock",
      name: "岩オブジェクト",
      image: "map/img_tile/rpg_objects/rock_cluster_01.png",
      passable: false,
      tags: ["object", "rock", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    water: {
      id: "water",
      name: "水辺",
      image: "map/img_tile/rpg_village/water_deep_01.png",
      passable: false,
      tags: ["water", "block"],
    },
    waterShore: {
      id: "waterShore",
      name: "水際",
      image: "map/img_tile/rpg_village/water_shore_01.png",
      passable: false,
      tags: ["water", "shore", "block"],
    },
    flowerMeadow: {
      id: "flowerMeadow",
      name: "花畑草地",
      image: "map/img_tile/rpg_village/flower_meadow_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    darkGrass: {
      id: "darkGrass",
      name: "暗い草地",
      image: "map/img_tile/rpg_village_extra/dark_grass_01.png",
      passable: true,
      tags: ["ground", "grass"],
    },
    wildflowerMeadow: {
      id: "wildflowerMeadow",
      name: "野花の草地",
      image: "map/img_tile/rpg_village_extra/wildflower_meadow_02.png",
      passable: true,
      tags: ["ground", "decoration", "flower"],
    },
    mossyGrass: {
      id: "mossyGrass",
      name: "苔むした草地",
      image: "map/img_tile/rpg_village_extra/mossy_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "moss"],
    },
    wornGrass: {
      id: "wornGrass",
      name: "踏まれた草地",
      image: "map/img_tile/rpg_village_extra/worn_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "blend"],
    },
    cobblestonePath: {
      id: "cobblestonePath",
      name: "丸石道",
      image: "map/img_tile/rpg_village_extra/cobblestone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    crackedStonePath: {
      id: "crackedStonePath",
      name: "ひび割れ石道",
      image: "map/img_tile/rpg_village_extra/cracked_stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    stonePath: {
      id: "stonePath",
      name: "石道",
      image: "map/img_tile/rpg_village/stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    farmRows: {
      id: "farmRows",
      name: "畑のうね",
      image: "map/img_tile/rpg_village_extra/farm_rows_01.png",
      passable: true,
      tags: ["ground", "farm"],
    },
    sandGround: {
      id: "sandGround",
      name: "砂地",
      image: "map/img_tile/rpg_village_extra/sand_ground_01.png",
      passable: true,
      tags: ["ground", "sand"],
    },
    mudGround: {
      id: "mudGround",
      name: "ぬかるみ",
      image: "map/img_tile/rpg_village_extra/mud_ground_01.png",
      passable: true,
      tags: ["ground", "mud"],
    },
    shallowWater: {
      id: "shallowWater",
      name: "浅瀬",
      image: "map/img_tile/rpg_village_extra/shallow_water_01.png",
      passable: true,
      tags: ["ground", "water", "shallow"],
    },
    marshGrass: {
      id: "marshGrass",
      name: "湿地草",
      image: "map/img_tile/rpg_village_extra/marsh_grass_01.png",
      passable: true,
      tags: ["ground", "marsh"],
    },
    cliffTopGrass: {
      id: "cliffTopGrass",
      name: "崖上草地",
      image: "map/img_tile/rpg_village_extra/cliff_top_grass_01.png",
      passable: true,
      tags: ["ground", "cliff"],
    },
    forestShadowGround: {
      id: "forestShadowGround",
      name: "森影の地面",
      image: "map/img_tile/rpg_village_extra/forest_shadow_ground_01.png",
      passable: true,
      tags: ["ground", "forest", "shadow"],
    },
    plazaEarth: {
      id: "plazaEarth",
      name: "広場の土",
      image: "map/img_tile/rpg_village_extra/plaza_earth_01.png",
      passable: true,
      tags: ["ground", "road", "village"],
    },
    pineTree: {
      id: "pineTree",
      name: "針葉樹オブジェクト",
      image: "map/img_tile/rpg_objects/tree_pine_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    flowerPatchObject: {
      id: "flowerPatchObject",
      name: "花かざり",
      image: "map/img_tile/rpg_objects/flower_patch_01.png",
      passable: true,
      tags: ["object", "decoration", "flower"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stump: {
      id: "stump",
      name: "切り株",
      image: "map/img_tile/rpg_objects/stump_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fallenLog: {
      id: "fallenLog",
      name: "倒木",
      image: "map/img_tile/rpg_objects/fallen_log_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    weeds: {
      id: "weeds",
      name: "草むら飾り",
      image: "map/img_tile/rpg_objects/weeds_01.png",
      passable: true,
      tags: ["object", "decoration", "grass"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fence: {
      id: "fence",
      name: "柵",
      image: "map/img_tile/rpg_objects/fence_01.png",
      passable: false,
      tags: ["object", "fence", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    crate: {
      id: "crate",
      name: "木箱",
      image: "map/img_tile/rpg_objects/crate_01.png",
      passable: false,
      tags: ["object", "box", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    barrel: {
      id: "barrel",
      name: "樽",
      image: "map/img_tile/rpg_objects/barrel_01.png",
      passable: false,
      tags: ["object", "barrel", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    well: {
      id: "well",
      name: "井戸",
      image: "map/img_tile/rpg_objects/well_01.png",
      passable: false,
      tags: ["object", "well", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    lampPost: {
      id: "lampPost",
      name: "街灯",
      image: "map/img_tile/rpg_objects/lamp_post_01.png",
      passable: false,
      tags: ["object", "lamp", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stoneMarker: {
      id: "stoneMarker",
      name: "石碑",
      image: "map/img_tile/rpg_objects/stone_marker_01.png",
      passable: false,
      tags: ["object", "stone", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    bridgePlank: {
      id: "bridgePlank",
      name: "木橋",
      image: "map/img_tile/rpg_objects/bridge_plank_01.png",
      passable: true,
      tags: ["object", "bridge", "wood"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -24,
    },
    door: {
      id: "door",
      name: "入口",
      image: null,
      passable: true,
      tags: ["event", "door"],
    },
    sign: {
      id: "sign",
      name: "看板",
      image: "map/img_tile/rpg_objects/signpost_01.png",
      passable: false,
      tags: ["object", "event", "decoration", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
  };

  window.HEALER_TILE_MAPS = {
    // Template only. Copy this when adding a new map.
    template: {
      id: "template",
      name: "タイルマップ雛形",
      tileSize: 48,
      width: 0,
      height: 0,
      defaultTile: "grass",
      layers: [
        { id: "ground", name: "地面", tiles: [] },
        { id: "object", name: "配置物", tiles: [] },
        { id: "event", name: "イベント", tiles: [] },
      ],
      events: [],
    },

    forestTest01: {
      id: "forestTest01",
      name: "森テスト01",
      tileSize: 48,
      width: 12,
      height: 8,
      defaultTile: "grass",
      layers: [
        {
          id: "ground",
          name: "地面",
          tiles: [
            "grass", "grass", "grass", "grass", "road", "road", "grass", "grass", "grass", "grass", "grass", "grass",
            "grass", "grass", "grass", "road", "road", "road", "road", "grass", "grass", "grass", "grass", "grass",
            "grass", "grass", "road", "road", "grass", "grass", "road", "road", "grass", "grass", "grass", "grass",
            "grass", "road", "road", "grass", "grass", "grass", "grass", "road", "road", "grass", "grass", "grass",
            "grass", "road", "grass", "grass", "grass", "soil", "soil", "grass", "road", "grass", "grass", "grass",
            "grass", "road", "road", "grass", "soil", "soil", "soil", "grass", "road", "road", "grass", "grass",
            "grass", "grass", "road", "road", "grass", "grass", "grass", "road", "road", "grass", "grass", "grass",
            "grass", "grass", "grass", "road", "road", "road", "road", "road", "grass", "grass", "grass", "grass",
          ],
        },
        {
          id: "object",
          name: "配置物",
          tiles: [
            "tree", null, null, null, null, null, null, null, null, "tree", "tree", "tree",
            null, null, "tree", null, null, null, null, null, null, null, "rock", null,
            null, null, null, null, null, "water", "water", null, null, null, null, null,
            "tree", null, null, null, null, "water", "water", null, null, null, null, "tree",
            "tree", null, null, null, null, null, null, null, null, null, null, "tree",
            null, null, null, "rock", null, null, null, null, null, null, null, null,
            null, "tree", null, null, null, null, null, null, null, "sign", null, null,
            "tree", "tree", null, null, null, null, null, null, null, null, "tree", "tree",
          ],
        },
        {
          id: "event",
          name: "イベント",
          tiles: [
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, "sign", null, null,
            null, null, null, null, null, "door", "door", null, null, null, null, null,
          ],
        },
      ],
      events: [
        {
          id: "forest_exit",
          name: "森の出口",
          type: "door",
          x: 5,
          y: 7,
          width: 2,
          height: 1,
          targetMap: null,
        },
        {
          id: "forest_sign",
          name: "森の看板",
          type: "inspect",
          x: 9,
          y: 6,
          text: "この先、森の奥。",
        },
      ],
    },

    tileShowcase01: {
      id: "tileShowcase01",
      name: "タイル確認01",
      tileSize: 48,
      width: 8,
      height: 6,
      defaultTile: "grass",
      layers: [
        {
          id: "ground",
          name: "地面",
          tiles: [
            "grass", "grassFlower", "grassDeep", "darkGrass", "wildflowerMeadow", "mossyGrass", "wornGrass", "grassPatchySoil",
            "road", "dirtGrassBlend", "dirtPathLeft", "soil", "cobblestonePath", "crackedStonePath", "stonePath", "plazaEarth",
            "floor", "farmRows", "sandGround", "mudGround", "shallowWater", "marshGrass", "water", "waterShore",
            "cliffTopGrass", "forestShadowGround", "grass", "grass", "grass", "grass", "grass", "grass",
            "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
            "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
          ],
        },
        {
          id: "terrain",
          name: "地形ブロック",
          tiles: [
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            "forestWallLeaf", "forestWallPine", "wall", null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
          ],
        },
        {
          id: "object",
          name: "配置物",
          tiles: [
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null,
            "tree", "pineTree", "shrubCluster", "flowerPatchObject", "rock", "stump", "fallenLog", "weeds",
            "sign", "fence", "crate", "barrel", "well", "lampPost", "stoneMarker", "bridgePlank",
          ],
        },
      ],
      events: [],
    },
  };
})();












