(() => {
  "use strict";

  // Map data edited by map collaborators.
  // Tile images are optional for now. When assets are ready, set image to a path
  // such as "map/img_tile/forest/grass.png".
  window.HEALER_TILE_DEFS = {
    test_grass: {
      id: "natural_grass",
      name: "明るい草地",
      image: "map/img_tile/rpg_village/grass_base_01.png",
      passable: true,
      tags: ["ground"],
    },
    grass: {
      id: "grass",
      name: "草地",
      image: "map/img_tile/base_seamless/grass_plain_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassPlain2: {
      id: "grassPlain2",
      name: "草地2",
      image: "map/img_tile/base_seamless/grass_plain_02.png",
      passable: true,
      tags: ["ground", "grass", "plain"],
    },
    grassFlower: {
      id: "grassFlower",
      name: "花の草地",
      image: "map/img_tile/rpg_village/grass_flower_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    grassBase: {
      id: "grassBase",
      name: "草地 ベース",
      image: "map/img_tile/rpg_village/grass_base_01.png",
      passable: true,
      tags: ["ground", "grass", "plain"],
    },
    grassDeep: {
      id: "grassDeep",
      name: "濃い草地",
      image: "map/img_tile/base_seamless/grass_dark_plain_01.png",
      passable: true,
      tags: ["ground", "deepGrass"],
    },
    grassPatchySoil: {
      id: "grassPatchySoil",
      name: "土まじりの草地",
      image: "map/img_tile/rpg_village/grass_patchy_soil_01.png",
      passable: true,
      tags: ["ground", "blend"],
    },
    road: {
      id: "road",
      name: "道",
      image: "map/img_tile/base_seamless/road_plain_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    dirtGrassBlend: {
      id: "dirtGrassBlend",
      name: "土と草の境目",
      image: "map/img_tile/rpg_village/dirt_grass_blend_01.png",
      passable: true,
      tags: ["ground", "road", "blend"],
    },
    dirtPathCenter: {
      id: "dirtPathCenter",
      name: "土の道 中央",
      image: "map/img_tile/rpg_village/dirt_path_center_01.png",
      passable: true,
      tags: ["ground", "road", "dirt"],
    },
    dirtPathDetail: {
      id: "dirtPathDetail",
      name: "土の道 模様",
      image: "map/img_tile/rpg_village/dirt_path_detail_01.png",
      passable: true,
      tags: ["ground", "road", "dirt", "decoration"],
    },
    dirtPathLeft: {
      id: "dirtPathLeft",
      name: "土の道 左寄せ",
      image: "map/img_tile/rpg_village/dirt_path_left_01.png",
      passable: true,
      tags: ["ground", "road"],
    },
    soil: {
      id: "soil",
      name: "土",
      image: "map/img_tile/base_seamless/soil_plain_01.png",
      passable: true,
      tags: ["ground"],
    },
    grassOverSoilPatch: {
      id: "grassOverSoilPatch",
      name: "草かぶせ土",
      image: "map/img_tile/grass_over_soil_patch.png",
      passable: true,
      tags: ["overlay", "ground", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeTop: {
      id: "grassEdgeTop",
      name: "草境界 上",
      image: "map/img_tile/grass_edge_top.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeBottom: {
      id: "grassEdgeBottom",
      name: "草境界 下",
      image: "map/img_tile/grass_edge_bottom.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeLeft: {
      id: "grassEdgeLeft",
      name: "草境界 左",
      image: "map/img_tile/grass_edge_left.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    grassEdgeRight: {
      id: "grassEdgeRight",
      name: "草境界 右",
      image: "map/img_tile/grass_edge_right.png",
      passable: true,
      tags: ["overlay", "edge", "grass"],
      drawWidth: 56,
      drawHeight: 56,
      drawOffsetX: -4,
      drawOffsetY: -4,
    },
    floor: {
      id: "floor",
      name: "木の床",
      image: "map/img_tile/rpg_village_extra/wood_plank_floor_01.png",
      passable: true,
      tags: ["ground", "indoor", "wood"],
    },
    wall: {
      id: "wall",
      name: "崖の壁",
      image: "map/img_tile/rpg_village_extra/cliff_wall_01.png",
      passable: false,
      tags: ["terrainBlock", "wall", "block"],
    },
    tree: {
      id: "tree",
      name: "広葉樹",
      image: "map/img_tile/rpg_objects/tree_leafy_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    forestWallLeaf: {
      id: "forestWallLeaf",
      name: "森の壁 葉",
      image: "map/img_tile/rpg_village/forest_wall_leaf_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestWallPine: {
      id: "forestWallPine",
      name: "森の壁 松",
      image: "map/img_tile/rpg_village/forest_wall_pine_01.png",
      passable: false,
      tags: ["terrainBlock", "forest", "block", "nature"],
    },
    forestHedgeOpen: {
      id: "forestHedgeOpen",
      name: "森の入口",
      image: "map/img_tile/rpg_village/forest_hedge_open_01.png",
      passable: true,
      tags: ["ground", "forest", "nature"],
    },
    shrubCluster: {
      id: "shrubCluster",
      name: "低木",
      image: "map/img_tile/rpg_objects/bush_01.png",
      passable: false,
      tags: ["object", "bush", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    villageShrubCluster: {
      id: "villageShrubCluster",
      name: "茂み",
      image: "map/img_tile/rpg_village/shrub_cluster_01.png",
      passable: false,
      tags: ["terrainBlock", "bush", "block", "nature"],
    },
    rock: {
      id: "rock",
      name: "岩",
      image: "map/img_tile/rpg_objects/rock_cluster_01.png",
      passable: false,
      tags: ["object", "rock", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    water: {
      id: "water",
      name: "水",
      image: "map/img_tile/base_seamless/water_plain_01.png",
      passable: false,
      tags: ["water", "block"],
    },
    waterDeep: {
      id: "waterDeep",
      name: "深い水",
      image: "map/img_tile/rpg_village/water_deep_01.png",
      passable: false,
      tags: ["water", "deep", "block"],
    },
    waterShore: {
      id: "waterShore",
      name: "水辺",
      image: "map/img_tile/rpg_village/water_shore_01.png",
      passable: false,
      tags: ["water", "shore", "block"],
    },
    flowerMeadow: {
      id: "flowerMeadow",
      name: "花畑",
      image: "map/img_tile/rpg_village/flower_meadow_01.png",
      passable: true,
      tags: ["ground", "decoration"],
    },
    darkGrass: {
      id: "darkGrass",
      name: "暗い草地",
      image: "map/img_tile/rpg_village_extra/dark_grass_01.png",
      passable: true,
      tags: ["ground", "grass"],
    },
    wildflowerMeadow: {
      id: "wildflowerMeadow",
      name: "野花の草地",
      image: "map/img_tile/rpg_village_extra/wildflower_meadow_02.png",
      passable: true,
      tags: ["ground", "decoration", "flower"],
    },
    mossyGrass: {
      id: "mossyGrass",
      name: "苔の草地",
      image: "map/img_tile/rpg_village_extra/mossy_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "moss"],
    },
    wornGrass: {
      id: "wornGrass",
      name: "すり減った草地",
      image: "map/img_tile/rpg_village_extra/worn_grass_01.png",
      passable: true,
      tags: ["ground", "grass", "blend"],
    },
    cobblestonePath: {
      id: "cobblestonePath",
      name: "石畳",
      image: "map/img_tile/rpg_village_extra/cobblestone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    crackedStonePath: {
      id: "crackedStonePath",
      name: "ひび割れ石道",
      image: "map/img_tile/rpg_village_extra/cracked_stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    stonePlain: {
      id: "stonePlain",
      name: "石地面",
      image: "map/img_tile/base_seamless/stone_plain_01.png",
      passable: true,
      tags: ["ground", "road", "stone", "plain"],
    },
    stonePath: {
      id: "stonePath",
      name: "石の道",
      image: "map/img_tile/rpg_village/stone_path_01.png",
      passable: true,
      tags: ["ground", "road", "stone"],
    },
    farmRows: {
      id: "farmRows",
      name: "畑",
      image: "map/img_tile/rpg_village_extra/farm_rows_01.png",
      passable: true,
      tags: ["ground", "farm"],
    },
    sandGround: {
      id: "sandGround",
      name: "砂地",
      image: "map/img_tile/rpg_village_extra/sand_ground_01.png",
      passable: true,
      tags: ["ground", "sand"],
    },
    mudGround: {
      id: "mudGround",
      name: "泥地",
      image: "map/img_tile/rpg_village_extra/mud_ground_01.png",
      passable: true,
      tags: ["ground", "mud"],
    },
    shallowWater: {
      id: "shallowWater",
      name: "浅瀬",
      image: "map/img_tile/rpg_village_extra/shallow_water_01.png",
      passable: true,
      tags: ["ground", "water", "shallow"],
    },
    marshGrass: {
      id: "marshGrass",
      name: "湿地草",
      image: "map/img_tile/rpg_village_extra/marsh_grass_01.png",
      passable: true,
      tags: ["ground", "marsh"],
    },
    cliffTopGrass: {
      id: "cliffTopGrass",
      name: "崖上草地",
      image: "map/img_tile/rpg_village_extra/cliff_top_grass_01.png",
      passable: true,
      tags: ["ground", "cliff"],
    },
    forestShadowGround: {
      id: "forestShadowGround",
      name: "森の影",
      image: "map/img_tile/rpg_village_extra/forest_shadow_ground_01.png",
      passable: true,
      tags: ["ground", "forest", "shadow"],
    },
    plazaEarth: {
      id: "plazaEarth",
      name: "広場の土",
      image: "map/img_tile/rpg_village_extra/plaza_earth_01.png",
      passable: true,
      tags: ["ground", "road", "village"],
    },
    pineTree: {
      id: "pineTree",
      name: "松",
      image: "map/img_tile/rpg_objects/tree_pine_01.png",
      passable: false,
      tags: ["object", "tree", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    flowerPatchObject: {
      id: "flowerPatchObject",
      name: "花壇",
      image: "map/img_tile/rpg_objects/flower_patch_01.png",
      passable: true,
      tags: ["object", "decoration", "flower"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stump: {
      id: "stump",
      name: "切り株",
      image: "map/img_tile/rpg_objects/stump_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fallenLog: {
      id: "fallenLog",
      name: "倒木",
      image: "map/img_tile/rpg_objects/fallen_log_01.png",
      passable: false,
      tags: ["object", "wood", "block", "nature"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    weeds: {
      id: "weeds",
      name: "雑草",
      image: "map/img_tile/rpg_objects/weeds_01.png",
      passable: true,
      tags: ["object", "decoration", "grass"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    fence: {
      id: "fence",
      name: "柵",
      image: "map/img_tile/rpg_objects/fence_01.png",
      passable: false,
      tags: ["object", "fence", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    crate: {
      id: "crate",
      name: "木箱",
      image: "map/img_tile/rpg_objects/crate_01.png",
      passable: false,
      tags: ["object", "box", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    barrel: {
      id: "barrel",
      name: "樽",
      image: "map/img_tile/rpg_objects/barrel_01.png",
      passable: false,
      tags: ["object", "barrel", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    well: {
      id: "well",
      name: "井戸",
      image: "map/img_tile/rpg_objects/well_01.png",
      passable: false,
      tags: ["object", "well", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    lampPost: {
      id: "lampPost",
      name: "街灯",
      image: "map/img_tile/rpg_objects/lamp_post_01.png",
      passable: false,
      tags: ["object", "lamp", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    stoneMarker: {
      id: "stoneMarker",
      name: "石碑",
      image: "map/img_tile/rpg_objects/stone_marker_01.png",
      passable: false,
      tags: ["object", "stone", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    bridgePlank: {
      id: "bridgePlank",
      name: "木の橋",
      image: "map/img_tile/rpg_objects/bridge_plank_01.png",
      passable: true,
      tags: ["object", "bridge", "wood"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -24,
    },
    door: {
      id: "door",
      name: "出入口",
      image: null,
      passable: true,
      tags: ["event", "door"],
    },
    sign: {
      id: "sign",
      name: "看板",
      image: "map/img_tile/rpg_objects/signpost_01.png",
      passable: false,
      tags: ["object", "event", "decoration", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    armorShopFront: {
      id: "armorShopFront",
      name: "防具屋",
      image: "map/img_tile/town_objects_front/armor_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "armor", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    weaponShopFront: {
      id: "weaponShopFront",
      name: "武器屋",
      image: "map/img_tile/town_objects_front/weapon_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "weapon", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    innFront: {
      id: "innFront",
      name: "宿屋",
      image: "map/img_tile/town_objects_front/inn_front_3x2.png",
      passable: false,
      tags: ["object", "building", "inn", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    requestOfficeFront: {
      id: "requestOfficeFront",
      name: "依頼所",
      image: "map/img_tile/town_objects_front/request_office_front_3x2.png",
      passable: false,
      tags: ["object", "building", "requestOffice", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    itemShopFront: {
      id: "itemShopFront",
      name: "アイテム屋",
      image: "map/img_tile/town_objects_front/item_shop_front_3x2.png",
      passable: false,
      tags: ["object", "building", "shop", "item", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    townHouseFront: {
      id: "townHouseFront",
      name: "町の民家 正面",
      image: "map/img_tile/town_objects_front/town_house_front_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    townHouseSideLeft: {
      id: "townHouseSideLeft",
      name: "町の民家 左向き",
      image: "map/img_tile/town_objects_front/town_house_side_left_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    townHouseSideRight: {
      id: "townHouseSideRight",
      name: "町の民家 右向き",
      image: "map/img_tile/town_objects_front/town_house_side_right_3x2.png",
      passable: false,
      tags: ["object", "building", "house", "decoration", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
  };

  const GENERATED_GROUND_GROUPS = [
    {
      idPrefix: "cityTile",
      folder: "city_generated",
      tag: "city",
      names: [
        "都市タイル 明るい石畳",
        "都市タイル 暗い石畳",
        "都市タイル 整った敷石",
        "都市タイル 紋章広場",
        "都市タイル 赤レンガ",
        "都市タイル 斜めレンガ",
        "都市タイル 古い石畳",
        "都市タイル 大判石床",
        "都市タイル 縁石道路",
        "都市タイル 角縁石道路",
        "都市タイル 水路",
        "都市タイル 水路角",
        "都市タイル 通路石床",
        "都市タイル 赤い屋根",
        "都市タイル 青い屋根",
        "都市タイル 白い装飾床",
      ],
    },
    {
      idPrefix: "townTile",
      folder: "town_generated",
      tag: "town",
      label: "街タイル",
    },
    {
      idPrefix: "villageTile",
      folder: "village_generated",
      tag: "village",
      label: "村タイル",
    },
    {
      idPrefix: "fieldTile",
      folder: "field_generated",
      tag: "field",
      label: "自然タイル",
    },
    {
      idPrefix: "demonCastleTile",
      folder: "demon_castle_generated",
      tag: "demonCastle",
      label: "魔王城タイル",
    },
  ];

  const SIDE_VIEW_BUILDING_GROUPS = [
    {
      category: "decorative",
      categoryLabel: "Decor",
      direction: "left",
      directionLabel: "Left",
      items: [
        ["01_cottage_thatch", 326, 292],
        ["02_log_cabin", 269, 256],
        ["03_stone_cottage_blue", 219, 300],
        ["04_wooden_shed", 208, 198],
        ["05_barn_red", 259, 293],
        ["06_watermill_house", 271, 279],
        ["07_windmill", 244, 292],
        ["08_watchtower", 233, 298],
        ["09_church", 269, 299],
        ["10_shrine", 233, 260],
        ["11_ruined_hut", 309, 252],
        ["12_ruined_stone_house", 248, 282],
        ["13_townhouse_2story", 255, 287],
        ["14_stone_workshop", 244, 263],
        ["15_magic_round_tower", 269, 300],
        ["16_snowy_log_cabin", 281, 261],
      ],
    },
    {
      category: "decorative",
      categoryLabel: "Decor",
      direction: "right",
      directionLabel: "Right",
      items: [
        ["01_cottage_thatch", 305, 245],
        ["02_log_cabin", 265, 256],
        ["03_stone_cottage_blue", 289, 256],
        ["04_wooden_shed", 291, 225],
        ["05_barn_red", 290, 242],
        ["06_watermill_house", 377, 253],
        ["07_windmill", 371, 256],
        ["08_watchtower", 265, 256],
        ["09_church", 299, 256],
        ["10_shrine", 357, 240],
        ["11_ruined_hut", 315, 240],
        ["12_ruined_stone_house", 359, 256],
        ["13_townhouse_2story", 289, 245],
        ["14_stone_workshop", 371, 241],
        ["15_magic_round_tower", 303, 256],
        ["16_snowy_log_cabin", 275, 244],
      ],
    },
    {
      category: "area_matched",
      categoryLabel: "Area",
      direction: "left",
      directionLabel: "Left",
      items: [
        ["01_grand_stone_hall", 304, 300],
        ["02_stone_townhouse", 267, 281],
        ["03_red_roof_house", 289, 258],
        ["04_bakery", 277, 267],
        ["05_farmhouse_with_field", 309, 300],
        ["06_round_straw_hut", 311, 285],
        ["07_forest_lodge", 299, 300],
        ["08_hide_shack", 281, 286],
        ["09_mountain_fort", 314, 299],
        ["10_snowy_house", 305, 286],
        ["11_desert_dome_house", 296, 282],
        ["12_desert_tower", 288, 296],
        ["13_swamp_shack", 308, 300],
        ["14_lakeside_house", 294, 292],
        ["15_demon_gate", 230, 300],
        ["16_demon_castle", 277, 300],
      ],
    },
    {
      category: "area_matched",
      categoryLabel: "Area",
      direction: "right",
      directionLabel: "Right",
      items: [
        ["01_grand_stone_hall", 252, 280],
        ["02_stone_townhouse", 295, 280],
        ["03_red_roof_house", 332, 247],
        ["04_bakery", 334, 250],
        ["05_farmhouse_with_field", 302, 281],
        ["06_round_straw_hut", 343, 281],
        ["07_forest_lodge", 333, 281],
        ["08_hide_shack", 312, 281],
        ["09_mountain_fort", 299, 281],
        ["10_snowy_house", 314, 281],
        ["11_desert_dome_house", 342, 281],
        ["12_desert_tower", 318, 281],
        ["13_swamp_shack", 299, 280],
        ["14_lakeside_house", 302, 266],
        ["15_demon_gate", 342, 268],
        ["16_demon_castle", 336, 280],
      ],
    },
  ];

  function padTileNumber(value) {
    return String(value).padStart(2, "0");
  }

  function toPascalCase(value) {
    return String(value)
      .split(/[^a-zA-Z0-9]+/)
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("");
  }

  function toReadableSideViewName(value) {
    return String(value)
      .split("_")
      .filter(Boolean)
      .map((part) => (/^\d+$/.test(part) ? part : part.charAt(0).toUpperCase() + part.slice(1)))
      .join(" ");
  }

  function createGeneratedGroundTiles() {
    const defs = {};

    GENERATED_GROUND_GROUPS.forEach((group) => {
      for (let index = 1; index <= 16; index += 1) {
        const id = `${group.idPrefix}${padTileNumber(index)}`;
        const row = padTileNumber(Math.floor((index - 1) / 4) + 1);
        const col = padTileNumber(((index - 1) % 4) + 1);
        const name = group.names ? group.names[index - 1] : `${group.label} ${padTileNumber(index)}`;

        defs[id] = {
          id,
          name,
          image: `map/img_tile/generated_ground/${group.folder}/tile_${row}_${col}.png`,
          passable: true,
          tags: ["ground", "generated", group.tag],
        };
      }
    });

    return defs;
  }

  function createSideViewBuildingDefs() {
    const defs = {};
    const maxDrawWidth = 144;
    const maxDrawHeight = 96;
    const footprintWidth = 3;
    const footprintHeight = 2;

    SIDE_VIEW_BUILDING_GROUPS.forEach((group) => {
      group.items.forEach(([fileStem, sourceWidth, sourceHeight]) => {
        const prefix = group.category === "decorative" ? "decorSide" : "areaSide";
        const directionPart = group.direction === "left" ? "Left" : "Right";
        const id = `${prefix}${directionPart}${toPascalCase(fileStem)}`;
        const scale = Math.min(maxDrawWidth / sourceWidth, maxDrawHeight / sourceHeight, 1);
        const drawWidth = Math.max(1, Math.round(sourceWidth * scale));
        const drawHeight = Math.max(1, Math.round(sourceHeight * scale));
        const drawOffsetX = Math.round((maxDrawWidth - drawWidth) / 2);
        const drawOffsetY = maxDrawHeight - drawHeight;

        defs[id] = {
          id,
          name: `${group.categoryLabel} ${group.directionLabel} ${toReadableSideViewName(fileStem)}`,
          image: `map/img_tile/building_drafts_20260715_000000/side_views/${group.category}/${group.direction}/${fileStem}.png`,
          passable: false,
          tags: ["object", "building", "sideView", group.category, group.direction, "decoration", "block"],
          drawWidth,
          drawHeight,
          drawOffsetX,
          drawOffsetY,
          footprintWidth,
          footprintHeight,
          placementAnchor: "bottomCenter",
        };
      });
    });

    return defs;
  }

  Object.assign(window.HEALER_TILE_DEFS, createGeneratedGroundTiles(), createSideViewBuildingDefs(), {
    caveFloor01: {
      id: "caveFloor01",
      name: "Cave Floor 01",
      image: "map/img_tile/cave/cave_floor_01.png",
      passable: true,
      tags: ["ground", "cave", "rock"],
    },
    caveFloor02: {
      id: "caveFloor02",
      name: "Cave Floor 02",
      image: "map/img_tile/cave/cave_floor_02.png",
      passable: true,
      tags: ["ground", "cave", "rock", "variation"],
    },
    caveFloorCracked01: {
      id: "caveFloorCracked01",
      name: "Cave Floor Cracked 01",
      image: "map/img_tile/cave/cave_floor_cracked_01.png",
      passable: true,
      tags: ["ground", "cave", "rock", "cracked"],
    },
    caveFloorWet01: {
      id: "caveFloorWet01",
      name: "Cave Floor Wet 01",
      image: "map/img_tile/cave/cave_floor_wet_01.png",
      passable: true,
      tags: ["ground", "cave", "rock", "wet", "variation"],
    },
    caveWall01: {
      id: "caveWall01",
      name: "Cave Wall 01",
      image: "map/img_tile/cave/cave_wall_01.png",
      passable: false,
      tags: ["terrainBlock", "cave", "wall", "block", "rock"],
    },
    caveWallHorizontal01: {
      id: "caveWallHorizontal01",
      name: "Cave Wall Horizontal 01",
      image: "map/img_tile/cave/cave_wall_horizontal_01.png",
      passable: false,
      tags: ["terrainBlock", "cave", "wall", "horizontal", "block", "rock"],
    },
    caveWallVertical01: {
      id: "caveWallVertical01",
      name: "Cave Wall Vertical 01",
      image: "map/img_tile/cave/cave_wall_vertical_01.png",
      passable: false,
      tags: ["terrainBlock", "cave", "wall", "vertical", "block", "rock"],
    },
    caveCrystalBlue: {
      id: "caveCrystalBlue",
      name: "Cave Crystal Blue",
      image: "map/img_tile/cave/cave_crystal_blue.png",
      passable: false,
      tags: ["object", "cave", "crystal", "block", "decoration"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    caveStalagmite01: {
      id: "caveStalagmite01",
      name: "Cave Stalagmite 01",
      image: "map/img_tile/cave/cave_stalagmite_01.png",
      passable: false,
      tags: ["object", "cave", "rock", "stalagmite", "block"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    caveTorch01: {
      id: "caveTorch01",
      name: "Cave Torch 01",
      image: "map/img_tile/cave/cave_torch_01.png",
      passable: false,
      tags: ["object", "cave", "torch", "light", "decoration"],
      drawWidth: 96,
      drawHeight: 96,
      drawOffsetX: -24,
      drawOffsetY: -48,
    },
    cityRequestOfficeFront: {
      id: "cityRequestOfficeFront",
      name: "都市部 依頼所",
      image: "map/img_tile/city_objects_front/city_request_office_front.png",
      passable: false,
      tags: ["object", "building", "requestOffice", "city", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    cityArmorShopFront: {
      id: "cityArmorShopFront",
      name: "都市部 防具屋",
      image: "map/img_tile/city_objects_front/city_armor_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "armor", "city", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    cityInnFront: {
      id: "cityInnFront",
      name: "都市部 宿屋",
      image: "map/img_tile/city_objects_front/city_inn_front.png",
      passable: false,
      tags: ["object", "building", "inn", "city", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    cityWeaponShopFront: {
      id: "cityWeaponShopFront",
      name: "都市部 武器屋",
      image: "map/img_tile/city_objects_front/city_weapon_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "weapon", "city", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
    cityItemShopFront: {
      id: "cityItemShopFront",
      name: "都市部 アイテム屋",
      image: "map/img_tile/city_objects_front/city_item_shop_front.png",
      passable: false,
      tags: ["object", "building", "shop", "item", "city", "block"],
      drawWidth: 144,
      drawHeight: 96,
      drawOffsetX: 0,
      drawOffsetY: 0,
      footprintWidth: 3,
      footprintHeight: 2,
      placementAnchor: "bottomCenter",
    },
  });
})();
